### ISSUE TITLE
Type name 'Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier' is ambiguous

### ISSUE THREAD

**Issue by rangedsp** [Azure/azure-iot-remote-monitoring#101]
Reopening new issue because latest version in master is still broken.
![image](https://cloud.githubusercontent.com/assets/4970707/12500493/91992d5a-c118-11e5-9256-89e3ba5a766c.png)

Original issue https://github.com/Azure/azure-iot-remote-monitoring/issues/95

**Comment by jamesweb-ms** [comment]
Can you open a new azure powershell window and run: 

[appdomain]::CurrentDomain.GetAssemblies() |FT ManifestModule, ImageRuntimeVersion, GlobalAssemblyCache

and

Get-Module

**Comment by rangedsp** [comment]
Here you go:
![image](https://cloud.githubusercontent.com/assets/4970707/12501116/9a89641a-c11e-11e5-9ff9-b4a67f2981a0.png)

**Comment by jamesweb-ms** [comment]
Can you try out the Jamesweb-ImportLib branch?  I haven't seen that library explicitly loaded before.  Added a check to see if the library that needs to be loaded is already in the appdomain.

**Comment by aguilaaj** [comment]
Any update @rangedsp ?

**Comment by jamesweb-ms** [comment]
Fix checked in PR #102
