### ISSUE TITLE
Local build error: "Get-AzureResourceGroup" not recognized

### ISSUE THREAD

**Issue by dick** [Azure/azure-iot-remote-monitoring#104]
My local build is failing. Any ideas? I'm using the Developer Command Prompt for VS 2015 in admin mode, and Azure Powershell seems to be installed 1.0. 

Get-AzureResourceGroup : The term 'Get-AzureResourceGroup' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\dick\Documents\petropi-remote-monitoring\Common\Deployment\DeploymentLib.ps1:725 char:13
+     $null = Get-AzureResourceGroup -ErrorAction SilentlyContinue -Err ...
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureResourceGroup:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-AzureResourceGroup : The term 'Get-AzureResourceGroup' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\dick\Documents\petropi-remote-monitoring\Common\Deployment\PrepareIoTSample.ps1:36 char:26
+     $legacyNameExists = (Get-AzureResourceGroup -Tag @{Name="IotSuite ...
+                          ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureResourceGroup:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by aguilaaj** [comment]
Hi @dick - see #103 - let us know if deploying from the same branch works for you.

**Comment by jamesweb-ms** [comment]
Actually I believe the issue is version of Azure Powershell you are using.  You will need to uninstall 1.0 and install the version from last [September](https://github.com/Azure/azure-powershell/releases/tag/v0.9.8-September2015) as we have not updated our scripts to support the latest version.  Hopefully we will add that support this month

**Comment by dick** [comment]
Downgrading to Azure Powershell 0.9.7 fixed it. Thanks!
