### ISSUE TITLE
Cloud deployment why S2

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-iot-remote-monitoring#105]
Is it possible to do a cloud deployment with an S1 IoT hub? Will it be sufficient to change the default value from S2 to S1 in RemoteMonitoring.json ? 
Thanks

**Comment by wesselkranenborg** [comment]
This is, of course, possible when the S1 limits are sufficient. I changed it also in my deployment json file.

**Comment by aguilaaj** [comment]
Hi all, for guidance, you can see #93. Also, if you go into portal.azure.com and change the provisioned IoT Hub from S2 to S1, when you redeploy using build.cmd, we honor your changes.

**Comment by basimolimajeed** [comment]
Thank you @wesselkranenborg and aguilaaj. Clear now. Regards
