### ISSUE TITLE
Resource Microsoft.Eventhub/namespaces 'LocalRM' failed

### ISSUE THREAD

**Issue by levi106** [Azure/azure-iot-remote-monitoring#110]
VERBOSE: 15:27:55 - Template is valid.
VERBOSE: 15:28:00 - Create template deployment 'LocalMonitoring'.
VERBOSE: 15:28:09 - Resource Microsoft.Storage/storageAccounts 'localrm06619' provisioning status is succeeded
VERBOSE: 15:28:09 - Resource Microsoft.Storage/storageAccounts 'localrm06619' provisioning status is succeeded
New-AzureResourceGroupDeployment : 15:28:13 - Resource Microsoft.Eventhub/namespaces 'LocalRM' failed with message 'The
 specified service namespace is not available.'
At C:\temp\azure-iot-remote-monitoring\Common\Deployment\PrepareIoTSample.ps1:139 char:11
+ $result = New-AzureResourceGroupDeployment -ResourceGroupName $resour ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

VERBOSE: 15:28:17 - Resource Microsoft.DocumentDb/databaseAccounts 'localrmc851c' provisioning status is running
VERBOSE: 15:28:17 - Resource Microsoft.Devices/Iothubs 'LocalRM97d3f' provisioning status is running
VERBOSE: 15:30:40 - Resource Microsoft.Devices/Iothubs 'LocalRM97d3f' provisioning status is succeeded
VERBOSE: 15:30:48 - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups 'LocalRM97d3f/events/rulescg'
provisioning status is succeeded
VERBOSE: 15:30:48 - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups
'LocalRM97d3f/events/telemetrycg' provisioning status is succeeded
VERBOSE: 15:30:48 - Resource Microsoft.Devices/Iothubs/Iothubkeys 'LocalRM97d3f/iothubowner' provisioning status is
succeeded
VERBOSE: 15:30:48 - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups
'LocalRM97d3f/events/deviceinfocg' provisioning status is succeeded
VERBOSE: 15:30:56 - Resource Microsoft.StreamAnalytics/streamingjobs 'LocalRM-Telemetry' provisioning status is running
VERBOSE: 15:31:12 - Resource Microsoft.DocumentDb/databaseAccounts 'localrmc851c' provisioning status is succeeded
VERBOSE: 15:31:15 - Resource Microsoft.DocumentDb/databaseAccounts 'localrmc851c' provisioning status is succeeded
VERBOSE: 15:32:58 - Resource Microsoft.StreamAnalytics/streamingjobs 'LocalRM-Telemetry' provisioning status is
succeeded
WARNING: The output object of this cmdlet will be modified in a future release.
WARNING: The output object of this cmdlet will be modified in a future release.
Provisioing failed
At C:\temp\azure-iot-remote-monitoring\Common\Deployment\PrepareIoTSample.ps1:144 char:5
+     throw "Provisioing failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Provisioing failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Provisioing failed

**Comment by CPardun** [comment]
We get the same error. Unfortunatly we can't deploy the IoT project to an Azure account.

**Comment by wesselkranenborg** [comment]
For this bug there was today a pull request (#112) merged. I fixed some other deployment issues and created another pull request for this (#114). This one is still pending but you can take a look at it.

**Comment by jamesweb-ms** [comment]
I have a fix in code review.  Hope to release it to master today.

**Comment by CPardun** [comment]
Thanks, but how can I downlaod Azure PowerSehll 1.3? I get Version 1.4...Can't find the old version.

**Comment by wesselkranenborg** [comment]
I also used 1.0.4. This also works (after you apply my fixes in #114).

**Comment by CPardun** [comment]
So is your fix online to doneload the newest master?

**Comment by wesselkranenborg** [comment]
After I downloaded the latest master and applied the changes in #114 it worked for me a few hours ago.

**Comment by jamesweb-ms** [comment]
Unfortunately #114 will not fix this issue as its with Servicebus not Websites.  While that same cmdlet also supports checking servicebus, it does not support docdb nor iothub.  It is also likely this cmdlet will be deprecated in the future when the ARM team releases support for CheckName -ResourceProvider functionality.

**Comment by wesselkranenborg** [comment]
You are right, my bad, didn't read good enough. It looked like the issues I was facing with a cloud deployment.

**Comment by jamesweb-ms** [comment]
That said, I do like avoiding poisoning website name in local cache.  Let me see if I can incorporate your change.

**Comment by CPardun** [comment]
I try a LOCAL deployment with the latest master and [https://github.com/Azure/azure-iot-remote-monitoring/pull/114](url) but I also get error.

Found application 'localApp'
Found ServicePrincipal 'localApp'
Invoke-RestMethod : {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient
privileges to complete the operation."}}}
In C:\Workspaces\MS\Azure_IoT\Common\Deployment\DeploymentLib.ps1:726 Zeichen:19
+ ...   $result = Invoke-RestMethod -Method "POST" -Uri $uri -Headers @{"Au ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Successfully assigned user to application '' as role 'Admin'
2016-02-18T21:02:29.6384390+01:00 - AADTenant changed to xxx-xxx
2016-02-18T21:02:29.6540605+01:00 - AADMetadataAddress changed to https://login.windows.net/xxxx-xxx-xx
dc0d8378/FederationMetadata/2007-06/FederationMetadata.xml
2016-02-18T21:02:29.6696868+01:00 - AADAudience changed to https://localhost:44305/iotsuite
2016-02-18T21:02:29.6696868+01:00 - AADRealm changed to https://localhost:44305/iotsuite
Suite name: LocalRM
DocDb Name: localrm70161
Storage Name: localrm50762
IotHub Name: LocalRM88cf9
Servicebus Name: LocalRM
AAD Tenant: xxxx-xxx-xxxx
ResourceGroup Name: LocalRM
Deployment template path: C:\Workspaces\MS\Azure_IoT\Common\Deployment\LocalMonitoring.json
Provisioning resources, if this is the first time, this operation can take up 10 minutes...
AUSFÜHRLICH: 21:02:31 - Create template deployment 'LocalMonitoring'.
AUSFÜHRLICH: 21:02:36 - Resource Microsoft.Storage/storageAccounts 'localrm50762' provisioning status is succeeded
AUSFÜHRLICH: 21:02:36 - Resource Microsoft.Devices/Iothubs 'LocalRM88cf9' provisioning status is running
New-AzureRmResourceGroupDeployment : 21:02:36 - Resource Microsoft.Eventhub/namespaces 'LocalRM' failed with message
'The specified service namespace is not available.'
In C:\Workspaces\MS\Azure_IoT\Common\Deployment\PrepareIoTSample.ps1:136 Zeichen:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

AUSFÜHRLICH: 21:02:36 - Resource Microsoft.Storage/storageAccounts 'localrm50762' provisioning status is succeeded
AUSFÜHRLICH: 21:02:38 - Resource Microsoft.DocumentDb/databaseAccounts 'localrm70161' provisioning status is running

I didn't understand the **_Authorization_RequestDenied". I have full access.

**Comment by jamesweb-ms** [comment]
I'll be creating a pull request shortly for this issue: "Resource Microsoft.Eventhub/namespaces 'LocalRM' failed with message 'The specified service namespace is not available.'"

Background...  The basename we use for local deployment is LocalRM.  The code checks DNS to see if the name is available, in this case LocalRM for eventhub appears available, but is actually assigned to a subscription that is suspended.  The ideal fix is to use a 'CheckName' call, but Azure Resource Manager currently does not have a consistent way to do this (it I planned though).

**Comment by jamesweb-ms** [comment]
P.S. I've been replying from phone, which is why I haven't just fixed it already.  :-)

Back in my office in a few minutes.

**Comment by jamesweb-ms** [comment]
@CPardun Merged #115 to master.  Try it again.  Will follow up with @wesselkranenborg on his change.  We will probably want to take the change for website as that was only place we were checking that name (even though there is support in the GetUniqueResourceName for it).

**Comment by CPardun** [comment]
Thanks a lot...Meanwhile I try a CLOUD deployment and get this error;

Microsoft.StreamAnalytics/streamingjobs
RESSOURCEN-ID/subscriptions/xxx-xxx-xxx/resourceGroups/iotremmon/providers/Microsoft.StreamAnalytics/streamingjobs/iotremmon-Rules
STATUSMESSAGE{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'."}}
RESSOURCEiotremmon-Rules

**Comment by CPardun** [comment]
I try a LOCAL deplyoment with master and #115 but I get this error: (Info: GUIDS are removed!)

C:\Workspaces\MS\Azure_IoT>C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -Comm
and C:\Workspaces\MS\Azure_IoT\\Common\Deployment\PrepareIoTSample.ps1 -environmentName local -configuration Debug
WARNUNG: This script Azure Cmdlets was tested with 1.0.3
WARNUNG: Found 1.0.4 installed; continuing, but errors might occur
Library WindowsAzure.ServiceBus not found, loading...
Loading Microsoft.ServiceBus.dll Assembly ...
Signed into Azure already
Trying to use saved profile C:\Workspaces\MS\Azure_IoT\Common\Deployment\..\..\xxxx@xxxxx.user
Select-AzureSubscription : The subscription id xxxxx-xxxx-xxxx-xxxx-xxxxxxxx doesn't exist.
Parametername: id
In C:\Workspaces\MS\Azure_IoT\Common\Deployment\DeploymentLib.ps1:819 Zeichen:5
+     Select-AzureSubscription -SubscriptionId $global:SubscriptionId
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Select-AzureSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SelectAzureSubscriptionCommand

With previous version this error don't occure.

**Comment by CPardun** [comment]
@jamesweb-ms: It's realy an issue with #115 that the " The subscription id xxxxx-xxxx-xxxx-xxxx-xxxxxxxx doesn't exist." error occur. On master with #114 it works.

**Comment by jamesweb-ms** [comment]
If you run "select-azuresubscription" in powershell, do you see subscriptions, or do you get any other messages?

**Comment by jamesweb-ms** [comment]
Also, try running "remove-azureaccount" from powershell and re-run build local to see if this is a cache issue.  @wesselkranenborg removed that line from #114 and it isn't needed anymore.  Once he merges my changes, we'll take his pull request.

**Comment by jamesweb-ms** [comment]
Oh, and missed the stream analytics failure.  This is an issue they have with DNS as well.  They are working on switching to non-caching vip, but in meantime, they have a chance to fail during creates (they can't resolve storage, IotHub, or EventHub hostnames).  If you re-run with the same name, it should succeed now.

**Comment by jamesweb-ms** [comment]
Just merged #114 to master that should address your issue.

**Comment by CPardun** [comment]
I try both deploys again. In both case I must do it twice to deploy it successfully! After deployment I try to access the webs and in both cases I get an error after trying to login. I get "We recieve an invalid rewuest...."Something like this. I notice that the Microsoft login service try to redirect but it fails with the above error!

Any ideas?

**Comment by wesselkranenborg** [comment]
Your error is indicating that you don't have the necessary permissions in your AAD tenant to add appRoleAssignments. Are you administrator of that AAD tenant?

I assume you are talking about this error: https://github.com/Azure/azure-iot-remote-monitoring/issues/110#issuecomment-185894484.

**Comment by CPardun** [comment]
Thanks a lot. I figure it out. I forgot to configure the authenification. In my cases I use Azure AD. It works now.

One question:
How can I debug the Azure IoT project. I deploy the projetc to Azure via build.cmd local. Everything goes right. Than I start VS 2015 and run the project but I got the same error that a invalid request is recieved. Is there anything I must configure in the Azure portal?

Thanks in advance.

**Comment by jamesweb-ms** [comment]
Looks like original issue is now resolved, so closing.  Please open a new issue if you are still having issues with local debugging.
