### ISSUE TITLE
Use Test-AzureName instead of HostEntryExists

### ISSUE THREAD

**Issue by wesselkranenborg** [Azure/azure-iot-remote-monitoring#113]
In DeploymentLib.ps1 on line 824 you use your own function HostEntryExists. In our network configuration with caching proxies will this result in unexpected caching of this non-existing record for one hour.

Is it an option to use the Test-AzureName cmdlet for this?
I use Test-AzureName -Website $environmentName on this line and this doen't result in the not existing a-record of azurewebsites.net being cached as not existing.

**Comment by jamesweb-ms** [comment]
Unfortunately this cmdlet does not support DocDB nor IotHub, and based on the talks with the ARM team, this will be replaced in the future with a cmdlet that lets you CheckName -ResourceProvider and will work for all RP's.  Unfortunately the spec that backs this feature is not complete yet.  The reason this cmdlet is implemented the way it is (with -provider flag) is that each provider has implemented their own way of checking names.  Until ARM has a consistent way to check for names, we will need to rely on DNS.

That said, can you test the following powershell to see if it works (if 2nd line times out which it does in our environment, that won't help either) -
$dnslist = nslookup -type=ns azuredns-prd.net | ?{$_.Contains("internet address")} | %{$_.split('=')[1].Trim()}
nslookup -type=a "none32343.azure-devices.net"  $dnslist[0]

If it does work, we can add this as a first try to avoid caching (uses Azure non-caching vips).

**Comment by wesselkranenborg** [comment]
You are right about the -provider flags. That's also the reason I don't implemented this in the HostEntryExists function but on this place. At this place I was only facing the problem.

Currently I'm at home and I am facing this problem at the office. When I'm in the office again I will try your suggestion and let you know. This will be around 8.00 a.m. (CET/GMT+1).

**Comment by wesselkranenborg** [comment]
Also good to know that this cmdlet will be replaced by another cmdlet. I use it in a lot of other scripts as well.

**Comment by wesselkranenborg** [comment]
This fix doesn't work for me. I only get non-authoritative answers from the internal dns proxy so "internet address" is not found.

When I use the non-authoritative answer and use the nameserver parameter I get a timeout when I try to access a DNS other then our proxy DNS servers. So this is an issue specific for our network.

I would suggest that the ARM team is coming with a final solution for this because I can't rely on DNS in our network setup :-)

```
PS C:\Users\wessel.kranenborg> $dnslist = nslookup -type=ns azuredns-prd.net | ?{$_.Contains("nameserver")} | %{$_.split('=')[1].Trim()}
nslookup -type=a "none32343.azure-devices.net" $dnslist[0]
nslookup : Non-authoritative answer:
At line:1 char:12
+ $dnslist = nslookup -type=ns azuredns-prd.net | ?{$_.Contains("namese ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Non-authoritative answer::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
nslookup : *** Request to UnKnown timed-out
At line:2 char:1
+ nslookup -type=a "none32343.azure-devices.net" $dnslist[0]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (*** Request to UnKnown timed-out:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  65.54.188.136

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
```
