### ISSUE TITLE
Problems caused by inconsistent deviceId/DeviceID/DeviceId case

### ISSUE THREAD

**Issue by ckarras** [Azure/azure-iot-remote-monitoring#119]
The samples in Azure IoT SDKs write deviceId with various uppercase/lowercase combinations. This causes problems in the Remote Monitoring sample application.

For example, in the Node.js sample in https://github.com/Azure/azure-iot-sdks/blob/master/node/device/samples/remote_monitoring.js, this ID is written as "DeviceID". This works fine for the deviceMetaData message, but not for "data" messages. In "data" messages, it should be written as "DeviceId". The reason is that, in azure-iot-remote-monitoring/DeviceAdministration/Infrastructure/Repository/DeviceTelemetryRepository.cs, there is a filter on the "DeviceId" property of a deserialized C# object. Since C# is case sensitive, deserialization will initialize the DeviceId to null if the property is named "DeviceID" instead of "DeviceId". When this happens, even though the telemetry data is written to a CSV in blob storage, the remote monitoring application doesn't display any data.

Note that also changing the "DeviceID" on the metadata message will cause similar problems: in this case, the remote monitoring application will fail to see that the device sent its metadata and it will be stuck in Pending state.

Also note that samples for the IoT SDKs in other languages use other variations of "DeviceId" as well.

A possible way to fix this would be, in the Stream Analytics queries on data coming from the devices, to add "DeviceId AS DeviceId" (or "DeviceID AS DeviceID" for metadata messages) in the SELECT clauses to convert any variations to the expected one.

**Comment by jamesweb-ms** [comment]
Thanks for report, we are looking at this.

**Comment by aguilaaj** [comment]
@ckarras - can you validate the latest fixes that went into master are resolving your issue?

**Comment by aguilaaj** [comment]
Fixed by #126

**Comment by ckarras** [comment]
@aguilaaj I retested with the latest version and could not reproduce the issue anymore, so I can confirm it is resolved.
