### ISSUE TITLE
DeploymentLib.ps1 is looking for "Azure PowerShell 2.5.1 or later", but the latest available version is 1.0.4?

### ISSUE THREAD

**Issue by ckarras** [Azure/azure-iot-remote-monitoring#122]
In DeploymentLib.ps1, I have an error at this line:
throw "Unable to find Azure.psd1 modules. Please install Azure Powershell 2.5.1 or later"

The most recent version of Azure PowerShell I could find was 1.0.4 and I confirmed it is installed. I also have the most recent version of the Azure SDK (2.8.2.1), but I can't find the file Azure.psd1 at the path where the script expects:

$modulePath = "$programFiles\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1"

I can however make it work by replacing the code with the following line:
$modulePath = "C:\Program Files\WindowsPowerShell\Modules\Azure\1.0.4\Azure.psd1"

This is more a workaround than a solution, since it is hard coded to version 1.0.4.

The message should be fixed to indicate the right product, so that we can easily look for and install the missing dependency. I'm guessing it's looking for version 2.5.1 of something other than Azure Powershell or Azure SDK.

**Comment by jamesweb-ms** [comment]
The loading code was for older versions of powershell (I made a note to update where we search), that said, I've seen the module not being loaded only after the initial install of Azure Powershell.  If you reboot, I think the module should be loaded and won't have to search (in the wrong place).  If you can confirm, that would be great.

As for the warning, we are going to make a change to only warn on Major.Minor version changes, not patch.  We'll clean up the error message at the same time.

**Comment by jamesweb-ms** [comment]
We have a fix for this issue in [Az_national_cloud branch](https://github.com/Azure/azure-iot-remote-monitoring/tree/az_national_cloud).  We are planning to merge this branch later today after some more testing.  If you want to give it a try and give use feedback, that would be great!

**Comment by aguilaaj** [comment]
Fixed in #151
