### ISSUE TITLE
Running web application issue after deploying "build.cmd local"

### ISSUE THREAD

**Issue by dewacorp** [Azure/azure-iot-remote-monitoring#124]
We follow this Wiki for deploying locally via build.cmd local command - https://github.com/Azure/azure-iot-remote-monitoring/wiki/Local-deployment-and-debugging and it looks successfully.

However when we run the Web and manage to see the portal BUT there is no data in dashboad and we checked under Devices on left handside there is no device on listed. So we added a new device and just spin and spin.

In VS 2015, the error is in infrastructure\Repository\DeviceRegistryRepository.cs line 41 

`Task.Run(() => _docDbRestUtil.InitializeDatabase()).Wait()`

Any ideas?

**UPDATE:** 
The issue is related on this: 
_The remote name could not be resolved: 'localrmd0819.documents.azure.com' _ and this is a bit odd due to DocumentDB Account exists ?!?!

**Comment by aguilaaj** [comment]
Hi @dewacorp - we'll update our wiki to include this: 
What you need to do to see the solution run e2e for a local deployment is run a separate instance of Visual Studio with each of the following projects set up as the Start Up project: 
- Web
- Simulator.WebJob
- EventProcessor.WebJob

**Comment by dewacorp** [comment]
Hi @aguilaaj ... when you said run a separate instance of VS set as start up projects means that right click on Remote Monitoring solution in VS and then select "Set Start Up projects" > Multiple start up projects > select those 3 projects ... does it?

**Comment by dewacorp** [comment]
Further issue on this one, when we run Start Up projects (Web, Simulator.WebJob and EventProcessor.WebJob), there is an exception error on Simulator.WebJon program.cs and we found soon after this in SimulatorModule.cs Load method.
![capture](https://cloud.githubusercontent.com/assets/13072589/13551911/a7c5e8aa-e39d-11e5-8b73-0fe21eff978e.PNG)


```
builder.RegisterType<DeviceLogic>()
                .As<IDeviceLogic>(); 
```
Any ideas?

**Comment by aguilaaj** [comment]
Did you walk through the prerequisites here: 
https://github.com/Azure/azure-iot-remote-monitoring/wiki/Set-up-development-environment-%28Windows%29 

Also, have you made any modifications from master?

**Comment by dewacorp** [comment]
Yes we did follow the prerequisites for setting up development environment. The only think different is that we are NOT using VS2013 ... we are using VS2015 instead. Does this matter?

**Comment by jamesweb-ms** [comment]
It should not matter unless you installed Azure SDK for 2013 instead of 2015.  Unfortunately you have to install the SDK that matches the VS version.  That said, I don't see the error exact error in your message.  Can you provide the full exception with stack?

**Comment by dewacorp** [comment]
Hi @jamesweb-ms ... We are using Azure SDK for VS2015. We also are installing Azure PowerShell.

The error is in EventProcessor\EventProcessor.WebJob\Program.cs

An unhandled exception of type 'System.Configuration.ConfigurationErrorsException' occurred in System.dll
Additional information: Couldn't find type for class Microsoft.WindowsAzure.Diagnostics.DiagnosticMonitorTraceListener, Microsoft.WindowsAzure.Diagnostics, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

Hope this helps.

**Comment by jamesweb-ms** [comment]
It can't find the azure SDK 2.7 library Microsoft.WindowsAzure.Diagnostics.  Please double check you have the 2015 version of 2.7 SDK installed.

**Comment by dewacorp** [comment]
@jamesweb-ms  ... we installed the Azure SDK 2.8.2 (latest one) that's why. It's working nicely now. Thanks for the help.

**Comment by anisha963** [comment]
Hello,
I have Azure SDK 2.9 installed for my Visual studio 2015. I am having the same issue.
Can you please give me how you revert back to Azure SDK 2.7?

Thank you in advance for your help.

**Comment by jamesweb-ms** [comment]
@anisha963  - please make sure you have pulled latest from master.  We have removed dependencies on Azure SDK.  Version should no longer matter.
