### ISSUE TITLE
What sort of license of this Iot Suite Remote Monitoring code solution?

### ISSUE THREAD

**Issue by dewacorp** [Azure/azure-iot-remote-monitoring#125]
Hi all

What sort of license of this Iot Suite Remote Monitoring code? Can we take this code and spin to other similar solution and extend into our version and run commercially? Obviously, we are still utilising Ms Azure platform. 

I'm appreciated your feedback.

Thanks
Valdy

**Comment by barnstee** [comment]
Hi Valdy, please read license.txt located in the root directory.
Cheers,
Erich
