### ISSUE TITLE
Problem with Simulator.WebJob

### ISSUE THREAD

**Issue by dewacorp** [Azure/azure-iot-remote-monitoring#127]
Hi there

We found this very strange that the Simulator.Webjob exe one has throwing an error (see below). But the telemetry history showing the data no problem (keep refreshing every 10 seconds). Occasionally, the telemetry data gets stuck and no data. The way to fix this is by restarting the app again.

In regards to Simulator.WebJob ... try to debug (step into it) and we couldn't find the error. 

![simulation_job_error](https://cloud.githubusercontent.com/assets/13072589/13720644/53eca0ec-e862-11e5-97a0-6249a78baf15.PNG)

**Comment by jamesweb-ms** [comment]
Looks like you're missing top of stack/exception...  Though it looks like an issue with IotHub.  Rest of stack would help determine what issue is.

**Comment by dewacorp** [comment]
Thanks for this. In VS2015, we did the Exception Settings instead and found the error something to do with sample device 4 and we accidentally disable this device in the web portal.

**Comment by aguilaaj** [comment]
@dewacorp - sounds like we can close this issue. Please reopen if you're still having issues.
