### ISSUE TITLE
When a new device is added, it is not reflected on the map

### ISSUE THREAD

**Issue by jcpierre** [Azure/azure-iot-remote-monitoring#131]
Hi,

I was trying out your demo application and noticed that when I add a device it does not appear in the map. Is there something else that I have to set?

Thanks.

JCP

**Comment by networkfusion** [comment]
Is the device real or simulated?

What is the devices status in the "Devices" tab?

**Comment by jcpierre** [comment]
it is simulated and the device is active.

**Comment by aguilaaj** [comment]
@jcpierre - my suspicion is your new device has the same location as one of your existing devices - you can validate by looking at the Latitude/Longitude in the Device Details pane for your devices. Feel free to edit the Latitude/Longitude for one of the duplicate simulated device locations and you should see your device.

**Comment by jcpierre** [comment]
@aguilaaj - Yes I did that but did not see a change. Question, is it working for you? if it is, I could provision another instance and test it again.

**Comment by jcpierre** [comment]
@aguilaaj - ahh! I see now, my changes was not dramatic enough. It is working, thank you for your help.

**Comment by aguilaaj** [comment]
Thanks for validating!
