### ISSUE TITLE
Cloud build trying to deploy storage account twice

### ISSUE THREAD

**Issue by kylecaulfield** [Azure/azure-iot-remote-monitoring#135]
When I try to deploy the build it will try to deploy the storage account twice, once when it uploads the webdeploy and once later:

{
  "error": {
    "code": "StorageAccountAlreadyExists",
    "message": "The storage account named kmciot already exists under the subscription."
  }
}

**Comment by kylecaulfield** [comment]
I resolved this by grabbing the latest code set and merging it with my changes.  I had another issue creating bing maps from the marketplace but got past it by creating one manually and deleting it.  Web searches had others with the same issues and they thought it was about accepting the license for the first time.

**Comment by davidjrh** [comment]
Check if the **storage account tags have been changed** through the Azure/PowerShell portal by somebody else, and are different than the ones specified on the ARM template.

Sounds like a bug on the ARM deployment system, tags should be able to be updated but it is currently failing for storage account resources. 

For more info see http://davidjrh.intelequia.com/2016/07/the-storage-account-already-exists.html
