### ISSUE TITLE
Deployment using azureiotsuite.com fails

### ISSUE THREAD

**Issue by TFilzmoser** [Azure/azure-iot-remote-monitoring#139]
When trying to deploy the remote Monitoring example using the Website https://www.azureiotsuite.com/ it fails during deployment of the Bing Maps API with a "Bad Request - Unable to convert varchar to int".

Steps to reproduce are fairly simple:
1.) Open https://www.azureiotsuite.com
2.) Click "Create a new solution"
3.) Select "Remote Monitoring"
4.) Enter a "Solution Name", select a Region and your subscription and click "Create"
5.) Get the error

**Comment by TFilzmoser** [comment]
Additional Info: It seems like this is a general error using the Bing API as adding the Bing API as a component using the Azure Portal also fails.

**Comment by jamesweb-ms** [comment]
Can you provide the specific error you see in:
https://portal.azure.com -> resource groups -> yoursolution -> Click link under Latest Deployments -> click linkedTemplate, click the failed bing deployment and provide details.

**Comment by TFilzmoser** [comment]
![bing maps error](https://cloud.githubusercontent.com/assets/15198365/14394954/2eefe632-fdcf-11e5-9666-31ffdd9c6ccc.PNG)

**Comment by jamesweb-ms** [comment]
BingMaps team has fixed this.  Please let us know if you are still seeing issues.

**Comment by TFilzmoser** [comment]
Looks good now, thank you for the quick support.
I will close this ticket.
