### ISSUE TITLE
Azure PowerShell 1.0.3 no where to be found

### ISSUE THREAD

**Issue by faister** [Azure/azure-iot-remote-monitoring#141]
build.cmd has a pre-requisite for Azure PowerShell 1.0.3, but I can't find seem to find this version any where. I tried a few methods:

- version 1.0.3 is missing from https://github.com/Azure/azure-powershell/releases?after=clu-2016012142 
- WebPI only has the latest version
- Install-Module -Name Azure -RequiredVersion 1.0.3 - this doesn't work either, error below:
WARNING: Package 'Azure' failed to download.
PackageManagement\Install-Package : Package 'Azure' failed to install.

Where can I find v 1.0.3?

**Comment by networkfusion** [comment]
You can install V1.0.4, but to be honest, deployment also works with the latest version (as long as you are using Azure SDK 2.7) with a warning about not using v1.0.3 of course.

**Comment by aguilaaj** [comment]
I'm following up with why the 1.0.3 release is missing from github, but you can see it in the PowerShell gallery here: https://www.powershellgallery.com/packages/Azure/1.0.3

**Comment by jamesweb-ms** [comment]
We have a fix for this issue in [Az_national_cloud branch](https://github.com/Azure/azure-iot-remote-monitoring/tree/az_national_cloud).  We are planning to merge this branch later today after some more testing.  If you want to give it a try and give use feedback, that would be great!

**Comment by aguilaaj** [comment]
Any version of Powershell 1.x is now usable with the preconfigured solution. See https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/dev-setup.md
