### ISSUE TITLE
403 errors after local build when running simulator job

### ISSUE THREAD

**Issue by robomotic** [Azure/azure-iot-remote-monitoring#144]
Hello guys,
I am getting a System.Net.WebException when I locally run either the SimulatorWebJob or the Web solution.
This is after running successfully the build.cmd local deployment.
The local.config.user seems to be properly filled with correct values.
However I am noticing something odd for instance let's take the IotHub section:
it contains the IotHubName and the ConnectionString, if I go on the Azure Dashboard on the corresponding hub in the shared access policies I don't see anything.
Is it possible that somehow the configuration script failed somehow to add the permissions?

**Comment by aguilaaj** [comment]
Make sure you have the correct prerequisites outlined here: https://github.com/Azure/azure-iot-remote-monitoring/wiki/Set-up-development-environment-%28Windows%29

**Comment by ckarras** [comment]
@aguilaaj How can I install Azure PowerShell 1.0.3? The page referenced on https://github.com/Azure/azure-iot-remote-monitoring/wiki/Set-up-development-environment-%28Windows%29 provides a link to install the latest version only, which is currently 1.3.0.

**Comment by aguilaaj** [comment]
See #141 - the package is here https://www.powershellgallery.com/packages/Azure/1.0.3

**Comment by robomotic** [comment]
I get multiple errors when I attempt to install that . what is the
reccomended way to uninstall the latest version which I believe to be the
issue ?

**Comment by aguilaaj** [comment]
@robomotic - what errors are you getting when you run:
`PS> Install-Module -Name Azure -RequiredVersion 1.0.3`

This may help if you need to uninstall: 
https://gist.github.com/devigned/b810efb0347ebe70713c

**Comment by robomotic** [comment]
Removing the old one and installing the new one worked now
