### ISSUE TITLE
Not able to create Azure IoT suite "Remote monitoring" solution with User having "Co-Admin" rights in the subscription

### ISSUE THREAD

**Issue by chiragmodi28** [Azure/azure-iot-remote-monitoring#145]
Hi

I am not able to create Azure IoT suite "Remote monitoring" solution with User having "Co-Admin" rights in the subscription. Is it mandatory to use "Service Administrator" to create IoT suite solution?

Please help me on that.

**Comment by aguilaaj** [comment]
See https://azure.microsoft.com/en-us/documentation/articles/iot-suite-permissions/

**Comment by aguilaaj** [comment]
If the issue persists please create a support request: https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade
