### ISSUE TITLE
Build and Deploy Code

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-remote-monitoring#148]
Hello

1. I have already deployed the remote monitoring solution through azureiotsuite.com. What is the build.cmd command to redeploy the code only without provisioning resources? 

2. How to run the web instance in Visual Studio and debug from the local machine? 

Thanks,

**Comment by jamesweb-ms** [comment]
1) If you use the same solution name as the name you used in AzureIotSuite.com, then it will update that solution instead of creating new resources.  eg. If you created "ContosoRM" in the portal, the command would be: build.cmd cloud debug ContosoRM

2) if you want to debug the cloud deployment locally do the following -
  - from repo root directory, copy ContosoRM.config.user created in previous to local.config.user
  - go to https://manage.windowsazure.com, select Active Directory, Select the active directory you chose when setting up in previous step, select applications, change to applications my company owns, click on app that matches your solution (eg. ContosoRMApp), click configure, add https://localhost:44305 to replyUrls, save
  - From visual studio, right click on Web and start a new debug instance.

Note: if you aren't an AAD admin for the directory you are currently using, you can create a new Active Directory (which will make you an admin) and run a deployment again using the new AAD (can't do this through portal), or ask your AAD admin to add the reply URL for you.

**Comment by ScottLiuGitHub** [comment]
For 1) I have created created a solution name "myservice" (replaced with the real name) from AzureIotSuite.com, So the resource group "myservice" has been created. 

When I tried to execute "build.cmd cloud debug myservice", I got the following error. It seems that the script still tried to create new resources instead of using existing: 

Unable to create unique name for resource myservice for url
servicebus.windows.net
At C:\development\azureiot\Common\Deployment\DeploymentLib.ps1:293 char:13
+             throw ("Unable to create unique name for resource {0} for url
{1}" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : OperationStopped: (Unable to creat...bus.windows
   .net:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to create unique name for resource myservice for url servicebus.windows.net

**Comment by jamesweb-ms** [comment]
That is odd... its generating a random number (200 times) and is still getting host found.  I have not seen this before.  Are you using same account/subscription for both?  Are you behind some firewall or corp network that prevents requests outbound from your computer?

**Comment by ScottLiuGitHub** [comment]
I only have one account and one subscription. But the subscription is under free trial. I actually changed the times to 500 but still getting the same error. I am not behind firewall or corp network. But I did create a separate solution directly from azureiotsuite.com but it is under a different resource group name.

**Comment by jamesweb-ms** [comment]
Your error indicates that all random names are already taken.  That is highly unlikely.

Please open powershell and test this function in your environment:

611 function HostEntryExists() 
612 { 
613     Param( 
614         [Parameter(Mandatory=$true,Position=0)] $hostName 
615     ) 
616     try 
617     { 
618         $hostName = [Net.Dns]::GetHostEntry($hostName) 
619         if ($hostName -ne $null) 
620         { 
621             Write-Verbose ("Found hostname: {0}" -f $hostName) 
622             return $true 
623         } 
624     } 
625     catch {} 
626     Write-Verbose ("Did not find hostname: {0}" -f $hostName) 
627     return $false 
628 }

**Comment by ScottLiuGitHub** [comment]
I will test it. 

To clarify, I only have one account and one subscription. But the subscription is under free trial. I am not behind firewall or corp network. 

Basically, I have two issues. 

1)  if I create a brand new solution from the code. I am getting the error from #147.  I actually changed the times to 500 but still getting the same error. 

2)  Because of the issue 1),  I created a separate solution directly from azureiotsuite.com and want to directly update the code without deploying resources. Now I am getting the error from this issue.

**Comment by ScottLiuGitHub** [comment]
Sorry, I am a Java developer and am switching to .net. How should I run this HostEntryExists function?

**Comment by jamesweb-ms** [comment]
open a Powershell cmd window and type:
[Net.Dns]::GetHostEntry('test.microsoft.com')

**Comment by ScottLiuGitHub** [comment]
PS C:\development\azurelocal\azure-iot-remote-monitoring\Common\Deployment> HostEntryExists
cmdlet HostEntryExists at command pipeline position 1
Supply values for the following parameters:
hostName: test.microsoft.com
False


C:\development\azurelocal\azure-iot-remote-monitoring\Common\Deployment> [Net.Dns]::GetHostEntry('test.microsoft.com')
Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"
At line:1 char:1
+ [Net.Dns]::GetHostEntry('test.microsoft.com')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SocketException

**Comment by jamesweb-ms** [comment]
I just added ability to pass arguments to powershell scripts.  Sync master, then in commandline run:
set SuiteArgs=-verbose
build cloud debug <myservicename>

There will be a lot more output.  Hopefully from that we can figure out why you are hitting DNS issues.
To turn this off, just run the following from cmdline (or close/open cmd shell)
set SuiteArgs=

**Comment by ScottLiuGitHub** [comment]
I ran build.cmd local and got the following error: 

WARNING: The output object type of this cmdlet will be modified in a future
release.
VERBOSE: 10:57:11 PM - Created resource group 'LocalRM' in location 'eastus'
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
VERBOSE: Found hostname: System.Net.IPHostEntry
Unable to create unique name for resource localrm for url blob.core.windows.net
At C:\development\azureiot2\Common\Deployment\DeploymentLib.ps1:293 char:13
+             throw ("Unable to create unique name for resource {0} for url
{1}" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : OperationStopped: (Unable to creat...ore.windows
   .net:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to create unique name for resource localr
   m for url blob.core.windows.net

**Comment by jamesweb-ms** [comment]
Sorry Scott, did not get time to look at this today.  The verbose output was incorrectly writing an object, not the hostname.  Can you pull and try again.  This won't fix your issue as the function still worked as expected, but should now show what names it was trying, which should get use closer to understanding why you are having this failure.

**Comment by ScottLiuGitHub** [comment]
I am seeing the exact same output. I fetched the latest master.

**Comment by jamesweb-ms** [comment]
You sure you didn't see new output, such as an actual HostName that changes?

I'm trying to figure out if this is a network issue where your dns provider always returns host found.  I've seen that in public networks where the host DNS sends host not found requests to a search engine.

**Comment by jtanner-msft** [comment]
Hi Scott - Are you still seeing this issue?  Have you tried performing a deployment on a different system or network to see if that resolved the issue?

**Comment by ScottLiuGitHub** [comment]
I am still getting the same error. I have tried a different subscription under the same account.

**Comment by ScottLiuGitHub** [comment]
It turned out it is the network. If I changed to my MI-FI using cell netwokr, it works. Not sure why the dns returned yes. I am on Verizon FIOS.

**Comment by ScottLiuGitHub** [comment]
Is there another DNS server I can point to?

**Comment by networkfusion** [comment]
8.8.8.8 google...

**Comment by ScottLiuGitHub** [comment]
I was finally able to deploy the solution without error. However, after I changed my code to the web component and deployed again. The build.cmd did not replace the content on the Azure. Below is the error message. 
Thanks!


Provisioning resources, if this is the first time, this operation can take up 10 minutes...
WARNING: The output object type of this cmdlet will be modified in a future release.
VERBOSE: 9:47:23 PM - Template is valid.
VERBOSE: 9:47:31 PM - Create template deployment 'RemoteMonitoringMapKey'.
VERBOSE: 9:47:44 PM - Resource Microsoft.Web/serverfarms 'deployasiaiot-plan' provisioning status is succeeded
VERBOSE: 9:47:44 PM - Resource Microsoft.Devices/Iothubs 'deployasiaiot' provisioning status is running
New-AzureRmResourceGroupDeployment : 9:47:44 PM - Resource Microsoft.Storage/storageAccounts 'deployasiaiot' failed with message 'The storage account named deployasiaiot already exists under the subscription.'
At C:\Development\vs2015\azure-iot-remote\Common\Deployment\PrepareIoTSample.ps1:195 char:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

VERBOSE: 9:47:56 PM - Resource Microsoft.Web/serverfarms 'deployasiaiot-jobsplan' provisioning status is succeeded
VERBOSE: 9:47:56 PM - Resource Microsoft.Servicebus/namespaces/eventHubs 'deployasiaiot/deployasiaiot-ehruleout' provisioning status is succeeded
VERBOSE: 9:47:56 PM - Resource Microsoft.Servicebus/namespaces 'deployasiaiot' provisioning status is succeeded
VERBOSE: 9:47:56 PM - Resource Microsoft.DocumentDb/databaseAccounts 'deployasiaiot' provisioning status is succeeded
VERBOSE: 9:47:56 PM - Resource Microsoft.DocumentDb/databaseAccounts 'deployasiaiot' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.StreamAnalytics/streamingjobs 'deployasiaiot-DeviceInfo' provisioning status is running
VERBOSE: 9:48:07 PM - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups 'deployasiaiot/events/telemetrycg' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups 'deployasiaiot/events/deviceinfocg' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Devices/Iothubs/Iothubkeys 'deployasiaiot/iothubowner' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Servicebus/namespaces/eventHubs 'deployasiaiot/deployasiaiot-ehout' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Devices/Iothubs/eventhubEndpoints/ConsumerGroups 'deployasiaiot/events/rulescg' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Servicebus/namespaces/authorizationRules 'deployasiaiot/RootManageSharedAccessKey' provisioning status is succeeded
VERBOSE: 9:48:07 PM - Resource Microsoft.Devices/Iothubs 'deployasiaiot' provisioning status is succeeded
VERBOSE: 9:50:14 PM - Resource Microsoft.StreamAnalytics/streamingjobs 'deployasiaiot-DeviceInfo' provisioning status is succeeded
New-AzureRmResourceGroupDeployment : 9:50:14 PM - "Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details."
At C:\Development\vs2015\azure-iot-remote\Common\Deployment\PrepareIoTSample.ps1:195 char:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

New-AzureRmResourceGroupDeployment : 'string' does not contain a definition for 'error'
At C:\Development\vs2015\azure-iot-remote\Common\Deployment\PrepareIoTSample.ps1:195 char:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], RuntimeBinderException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

WARNING: The output object type of this cmdlet will be modified in a future release.
WARNING: The output object type of this cmdlet will be modified in a future release.
VERBOSE: 9:50:19 PM - Updated resource group 'deployasiaiot' in location 'eastasia'
Provisioning failed
At C:\Development\vs2015\azure-iot-remote\Common\Deployment\PrepareIoTSample.ps1:200 char:5
+     throw "Provisioning failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Provisioning failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Provisioning failed

Error C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -Command C:\Development\vs2015\azure-iot-remote\\Common\Deployment\PrepareIoTSample.ps1 -environmentName deployasiaiot -configuration debug -verbose

**Comment by jamesweb-ms** [comment]
I'm closing the DNS issue.  Please open a new issue for deployment failure.  BTW - this looks like a storage issue that you will need to go to azure portal to get more details on.

**Comment by FelixXWS** [comment]
Hello,
I'm getting the same problem. Doesn't matter if I type build.cmd cloud or local. Deploying at https://www.azureiotsuite.com/ works...
@ScottLiuGitHub: How did you solve the problem that the deployment works with Developer Command Prompt? How can I test it if this is a problem with the DNS?
Thanks in advance.

**Comment by networkfusion** [comment]
@FelixXWS please see #421 ... I would suggest opening a new issue if not as things have moved on since this...
