### ISSUE TITLE
(Help) Deployment error

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#149]
OK, so I have to redeploy my current instance of the Remote Monitoring solution to 2 different subscriptions both with different errors, but one at a time, so.... 

SDK: 2.7.1
PS: 1.0.4
The first error I am getting is when it is trying to deploy the first streaming analytics job:

`New-AzureRmResourceGroupDeployment : 20:57:47 - Resource Microsoft.StreamAnalytics/streamingjobs
'surfacenet-staging-DeviceInfo' failed with message 'The resource operation completed with terminal provisioning state
'Failed'.'
At F:\Robin\Source\Repos\SurfaceNetIoTHub\Common\Deployment\PrepareIoTSample.ps1:136 char:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

Provisioning failed
At F:\Robin\Source\Repos\SurfaceNetIoTHub\Common\Deployment\PrepareIoTSample.ps1:141 char:5
+     throw "Provisioning failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Provisioning failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Provisioning failed`

Which terminates the deployment. In the portal, the streaming analytics job is started.

I am noticing that my subscription is suffering from a message that says "Error getting server events", but I have been trying this for 2 weeks now and am getting annoyed!

I have also noticed that on successive retries, rather than overriding the servicebus resource, a new one is created (not deleting the old one) with a random string after...

**Comment by aguilaaj** [comment]
Hi @networkfusion - can you create a service request at https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade
and mark category as IoT Suite? Up to you if you want to create 2 separate issues or just 1.

We may need to pull the logs for your subscription, region, etc.

**Comment by networkfusion** [comment]
Unfortunately I only have basic support and the only option available is to report it under "App and Service Availability" > "Quotas"... Is there any point in doing that?

**Comment by aguilaaj** [comment]
May I use your @networkfusion.co.uk mail to contact you re: subscriptionid, region, etc?

**Comment by networkfusion** [comment]
that's fine.

**Comment by networkfusion** [comment]
I haven't heard from anyone, but I have been able to deploy successfully (I am guessing someone has fixed the issue within azure portal) so I am closing this... Thanks.
