### ISSUE TITLE
Refresh command history after receiving command

### ISSUE THREAD

**Issue by hopitas** [Azure/azure-iot-remote-monitoring#154]
Hi,

The command history list should refresh after receiving command. Now if you send for example Ping command to device, the command history list shows "pending" until you refresh the page manually.

P.S. I want to thank you for this great software. This kind of solutions are exactly what is needed when fast prototyping IoT to customers!

**Comment by aguilaaj** [comment]
Thanks for the note @hopitas - we'll keep this one open as an enhancement for now. 
Feel free to post additional feature enhancements on our [Azure IoT UserVoice](https://feedback.azure.com/forums/321918-azure-iot)

**Comment by aguilaaj** [comment]
Thanks for the feedback, unfortunately we are marking this issue as won't fix for the time being. If you'd like to implement the changes yourself, we will happily review pull requests.
