### ISSUE TITLE
Azure IoT Suite Provisioning Failed

### ISSUE THREAD

**Issue by cnvery** [Azure/azure-iot-remote-monitoring#160]
Hi all,

I faced some issue on creating new Azure IoT Suite Remote Solution.

I created one solution under Southeast Asia region using Student Dreamspark subscription.

Instead of showing "Ready" in provisioned solutions screen, it showed "Provisioning failed".

However, the cause of error is due to "_Write Deployments Failed_"

3 Errors Under Write Deployments Failed & Its Reasons:
i)  microsoft.resources/deployments/write

> OPERATION NAME microsoft.resources/deployments/write
> STATUS Failed
> EVENT TIMESTAMP Wed May 04 2016 16:01:58 GMT+0800 (Malay Peninsula Standard Time)
> UTC TIMESTAMP Wed, 04 May 2016 08:01:58 GMT
> CALLER *****
> AUTHORIZATION 
> action:microsoft.resources/deployments/write role: scope:/subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/microsoft.resources/deployments/IotPortal
> RESOURCE URI /subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/microsoft.resources/deployments/IotPortal
> SUBSCRIPTION ID *****
> EVENT SUBMISSION TIMESTAMP Wed May 04 2016 16:02:09 GMT+0800 (Malay Peninsula Standard Time)
> OPERATION ID bfa292bd-8600-4251-8e6d-89bd210e5d0a
> CORRELATION ID 518a741b-2bcb-4a3b-8f62-69365dbcc4ee
> LEVEL Error
> RESOURCE GROUP InnovateTraffic
> RESOURCE PROVIDER Microsoft Resources
> CATEGORY Administrative

ii) Microsoft.Resources/deployments/write
> OPERATION NAME Microsoft.Resources/deployments/write
> STATUS Failed
> EVENT TIMESTAMP Wed May 04 2016 16:01:57 GMT+0800 (Malay Peninsula Standard Time)
> UTC TIMESTAMP Wed, 04 May 2016 08:01:57 GMT
> CALLER *****
> AUTHORIZATION 
> action:Microsoft.Resources/deployments/write role: scope:/subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/Microsoft.Resources/deployments/linkedTemplate
> RESOURCE URI /subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/Microsoft.Resources/deployments/linkedTemplate
> SUBSCRIPTION ID *****
> EVENT SUBMISSION TIMESTAMP Wed May 04 2016 16:02:09 GMT+0800 (Malay Peninsula Standard Time)
> OPERATION ID 7f287a2f-21d4-4aaa-af56-aa9c17894f74
> CORRELATION ID 518a741b-2bcb-4a3b-8f62-69365dbcc4ee
> LEVEL Error
> RESOURCE GROUP InnovateTraffic
> RESOURCE PROVIDER Microsoft Resources
> CATEGORY Administrative
> PROPERTIES 
> statusCode:BadRequest statusMessage:{"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.DocumentDb'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web,SuccessBricks.ClearDB'."}}

iii)  Microsoft.Resources/deployments/write

> OPERATION NAME Microsoft.Resources/deployments/write
> STATUS Failed
> EVENT TIMESTAMP Wed May 04 2016 16:01:57 GMT+0800 (Malay Peninsula Standard Time)
> UTC TIMESTAMP Wed, 04 May 2016 08:01:57 GMT
> CALLER *****
> AUTHORIZATION 
> action:Microsoft.Resources/deployments/write role: scope:/subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/Microsoft.Resources/deployments/linkedTemplate
> RESOURCE URI /subscriptions/23c556e9-392d-4af8-ae4f-3063cbe010fd/resourcegroups/InnovateTraffic/providers/Microsoft.Resources/deployments/linkedTemplate
> SUBSCRIPTION ID *****
> EVENT SUBMISSION TIMESTAMP Wed May 04 2016 16:02:09 GMT+0800 (Malay Peninsula Standard Time)
> OPERATION ID 1f306df3-97ae-48c4-8d9a-8712c2cd731d
> SUBSTATUS Bad Request (HTTP Status Code: 400)
> CORRELATION ID 518a741b-2bcb-4a3b-8f62-69365dbcc4ee
> HTTP REQUEST 
> clientRequestId:2ca2b0c7-bdb9-4b83-a411-c9b17684d192 clientIpAddress:40.76.215.167 method:PUT
> LEVEL Error
> RESOURCE GROUP InnovateTraffic
> RESOURCE PROVIDER Microsoft Resources
> CATEGORY Administrative
> PROPERTIES 
> statusCode:BadRequest serviceRequestId: statusMessage:{"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.DocumentDb'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web,SuccessBricks.ClearDB'."}}

Is there any solution for this?

Thank you.

**Comment by jamesweb-ms** [comment]
Can you use powershell to confirm your subscription doesn't have access to DocDB (and other resource provider namespaces)?

login-azurermaccount
Get-AzureRmResourceProvider

You need access to:
Microsoft.BingMaps
Microsoft.DocumentDB
Microsoft.ServiceBus
Microsoft.Devices
Microsoft.Storage
Microsoft.StreamAnalytics
Microsoft.Web

I suspect that the subscription type you are using is not allowed to create these resources.  I'm following up with ARM team and our PM's to confirm.

**Comment by aguilaaj** [comment]
Looks like DreamSpark usage is limited to
- Notification Hubs
- Azure Mobile Apps 
- SQL Database 
- Azure App Service Web Apps
- MySQL Database from ClearDB
- Visual Studio Application Insights
- Visual Studio Online 

from this link:
https://www.dreamspark.com/Product/Product.aspx?productid=99

**Comment by chrit-msft** [comment]
In reviewing the DreamSpark page there is a box for _Resources & Training_ which has the following link http://blogs.msdn.com/b/microsoft_student_developer_blog/archive/2015/04/09/using-microsoft-azure-for-students.aspx which provides a list of services which appear to be a subset of the ones on the main DreamSpark page.  Neither of these pages provide inclusion into enough services to provision an IoT Hub.  Please provide feedback using this link https://feedback.azure.com/forums/321918-azure-iot/suggestions/13367967-iot-features-free-for-dreamspark-user to encourage inclusion of the IoT features.

**Comment by aguilaaj** [comment]
@cnvery - feel free to create a 30 day trial: https://azure.microsoft.com/en-us/free/ and check out this doc for your demo purposes https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/configure-preconfigured-demo.md 

Closing for now. Thanks!
