### ISSUE TITLE
build.cmd does not work when having spaces in path to ps1 file

### ISSUE THREAD

**Issue by quadaloop** [Azure/azure-iot-remote-monitoring#164]
The command

@SET PublishCmd=%PowerShellCmd% %DeploymentScripts%\PrepareIoTSample.ps1 -environmentName %EnvironmentName% -configuration %Configuration% %SuiteArgs%

in file build.bat fails when the PrepareIoTSample.ps1 file is within a directory that contains spaces.

Using
@SET PublishCmd=%PowerShellCmd% "& ""%DeploymentScripts%\PrepareIoTSample.ps1""" -environmentName %EnvironmentName% -configuration %Configuration% %SuiteArgs%

fixed that issue for me.

**Comment by aguilaaj** [comment]
@jamesweb-ms can you take a look?
