### ISSUE TITLE
Error in DeploymentLib.ps1 (AccountKey access)

### ISSUE THREAD

**Issue by quadaloop** [Azure/azure-iot-remote-monitoring#165]
Around line 390: This line in DeploymentLib.ps1 did not work for me like present in github:
 $storageAccountKey = (Get-AzureRmStorageAccountKey -StorageAccountName $storageAccountName -ResourceGroupName $resourceGroupName).Key1

I had to replace it with:
 $storageAccountKey = (Get-AzureRmStorageAccountKey -StorageAccountName $storageAccountName -ResourceGroupName $resourceGroupName).Value[0]

**Comment by aguilaaj** [comment]
@jamesweb-ms can you take a look?

**Comment by VJDevloper** [comment]
$storageAccountKey = (Get-AzureRmStorageAccountKey -StorageAccountName $storageAccountName -ResourceGroupName $resourceGroupName).Get_Item(0).Value

Change line as above should work.

**Comment by jamesweb-ms** [comment]
This was fixed with #174
