### ISSUE TITLE
AAD App Id in multi tenant environment

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#166]
When deploying in a multi tenant environment (i.e. the solution is deployed to a different directory than AAD) website authentication is broken. this is because "Application is multi-tenant" is not turned on within the AAD apps configuration and the Permissions to other applications is also not configured. However this is made harder because the App Id is in the format [mydeploymentname]/iotsuite, but in order to turn on "Application is multi-tenant" the id needs to use a domain name linked to your AAD directory (usually in the format [directory].onmicrosoft.com) so I would propose that the app Id is updated to at least be [directory].onmicrosoft.com/[mydeploymentname] as this will make things easier for multi tenants to setup properly and also not deploy a new AAD app every deployment (when not already having a .config file)

**Comment by aguilaaj** [comment]
Thanks for the feedback, unfortunately we are marking this issue as won't fix for the time being. If you'd like to implement the changes yourself, we will happily review pull requests. 
In addition, please post on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/) for others to upvote the priority of this ask.

**Comment by networkfusion** [comment]
I am looking into how to achieve this. I am guessing I have to reference https://msdn.microsoft.com/en-us/library/azure/dn194090.aspx from deploymentlib.ps and then pass the result in as a parameter.
then change "identifierUris" within application.json to be "identifierUris": [ "{3}/{1}" ]

then all that should need to be done is change "availableToOtherTenants": false to true...

**Comment by networkfusion** [comment]
so for example change line 742 of deploymentlib to:
$addomain = Get-Domain -Status Verified
        $body = ReplaceFileParameters ("{0}\Application.json" -f $global:azurePath) -arguments @($global:site, $global:environmentName, $addomain[0])

**Comment by jamesweb-ms** [comment]
@networkfusion  - that approach sounds reasonable, though as Ariel mentioned, we are unlikely to take such a change at this time as it would not be backwards compatible (would result in duplicate applications unless we added more code to detect).

Also note, the {0}iotsuite identifierUris are also used on lines: 
* 734 (search)
* 746, 770, 792 (error messages)

Remote Monitoring app itself only uses the ApplicationId (set on line 758) so no changes there should be necessary.  That said, I have not tried using multitenant applications with Remote Monitoring so you are on your own here.  :)
