### ISSUE TITLE
 Localized string support

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-remote-monitoring#168]
I noticed that localized string support was added to the latest release. How do I utilize it? Thanks!

**Comment by networkfusion** [comment]
Click on the globe on the top bar of the webpage. you can then select the language you wish to use.

**Comment by aguilaaj** [comment]
Closing for now, let us know if you have additional questions/issues. 

![image](https://cloud.githubusercontent.com/assets/670242/15295313/c827c166-1b44-11e6-8639-8dab306b585c.png)
