### ISSUE TITLE
Logic Apps

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#169]
Logic apps are mentioned as being part of the architecture, however there doesn't seem to be any documentation... If logic apps are part of it, is there a good resource I can look at?

**Comment by aguilaaj** [comment]
I have an article on this in review. Hang tight for a day or so!

**Comment by aguilaaj** [comment]
@networkfusion - see https://azure.microsoft.com/en-us/documentation/articles/iot-suite-logic-apps-tutorial/
