### ISSUE TITLE
New-AzureRmResourceGroupDeployment - operation not permitted

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azure-iot-remote-monitoring#179]
... for name space 'Microsoft.Servicebus'

**Has anybody had a similar issue?**

![image](https://cloud.githubusercontent.com/assets/431978/15965382/c60689e8-2f1d-11e6-8aed-31388346183e.png)

The only changes I did were in RemoteMonitoring.json where I changed 
- iotHubTier from standard to "free", 
- webJobSku from Standard to Free
- webSku from Standard to Free
- IoTHubsku from S2 to F1 and 
- storageSku from Standard_GRS to Standard_LRS.

Execution: build.cmd cloud debug

**Comment by jtanner-msft** [comment]
Hello,

  Have you taken a look at this document that describes reducing the tiers of the IoT Suite components thru the portal once the Suite is deployed?
  https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/configure-preconfigured-demo.md 

  That should work fine so you can perform the deployment and then lower the levels so they are lower cost tiers.

  I’m not aware of anyone having deployed a suite with so many ‘Free’ tiers being used.  From an IoT Hub perspective please keep in mind that you are limited to a single ‘Free’ Iot Hub per Azure Subscription account, so if you already had one deployed somewhere you would have a failure in trying to provision a second one.  Similar limitations might also exist for the other services that you had listed.  The other thing is that if a Hub is created as either an S2 or S1 tier, it cannot be lowered down to the ‘Free’ tier.  It needs to be created as ‘Free’ from the start.

**Comment by lmiroslaw** [comment]
Original deployment did not work as well. Maybe there is something wrong with the subscription. I will report this to the Support Team.

**Comment by jtanner-msft** [comment]
I would suggest that you review these two pages to see if they can help you to address your permissions problems:

https://azure.microsoft.com/en-us/documentation/articles/iot-suite-faq/ 

https://azure.microsoft.com/en-us/documentation/articles/iot-suite-permissions/#faq 

If that doesn’t help, then going and creating your own AAD Tenant, and deploying into that with the build.cmd might help.  Initially please just try using the default tiers as they are configured in the solution.

Or if you haven’t done it already we also do offer a free one month trial that you can sign up for here: https://azure.microsoft.com/en-us/pricing/free-trial/

**Comment by lmiroslaw** [comment]
It turned out the remote monitoring demo is not available in the CSP Program.
