### ISSUE TITLE
Prevent device spoofing

### ISSUE THREAD

**Issue by ckarras** [Azure/azure-iot-remote-monitoring#191]
Currently, I can easily spoof a device when sending to the Remote Monitoring application. The only thing I need is a valid connection string for *any* device, but once a device is authenticated, it can impersonate any other device.

The reason is that the application uses the "DeviceID" in the JSON payload instead of the "ConnectionDeviceID" property that's automatically added by IoT Hub. The DeviceID in the payload does not have to match the DeviceID in the connection string.

In a Azure Stream Analytics query , this property can be read using IoTHub.ConnectionDeviceID.
In C#, this property can be read using:
object iotHubConnectionDeviceId;
eventData.SystemProperties.TryGetValue("iothub-connection-device-id", out iotHubConnectionDeviceId);

Since the Remote Monitoring solution is intended as a starting point for more complete solutions (or as guidance to build our own solutions), it would be important for it to include security practices.

**Comment by jamesweb-ms** [comment]
Fixed with change #197
