### ISSUE TITLE
Update Hosting Plan: "Cannot find user"

### ISSUE THREAD

**Issue by justsayno** [Azure/azure-iot-remote-monitoring#194]
This is a long shot but I am re-purposing an old project we built on top of this project when it was using 0.x Azure Powershell. We made some changes to the way the web app itself worked and added some things so I am trying to use the new latest deployment scripts and ARM template but have run into an issue I can't find a solution to.

The script gets and error on the event 'Update hosting plan' that results in this message:

```
{
  "Code": "NotFound",
  "Message": "Cannot find user.",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot find user."
    },
    {
      "Code": "NotFound"
    },
    {
      "ErrorEntity": {
        "Code": "NotFound",
        "Message": "Cannot find user.",
        "ExtendedCode": "09004",
        "MessageTemplate": "Cannot find user.",
        "Parameters": [],
        "InnerErrors": null
      }
    }
  ],
  "Innererror": null
}
```
Here is screenshot of the error in the portal:

![error1](https://cloud.githubusercontent.com/assets/4713713/16676992/b1d7caf0-4524-11e6-9354-98b34dbba468.PNG)

There are two instances of this event/error in the portal interface.

Everything else seems to work fine except there is another event that has an error:

![error2](https://cloud.githubusercontent.com/assets/4713713/16676993/b689ac44-4524-11e6-9770-2fd0a39b58bf.PNG)

Just for completeness here is a screenshot of the resource group after deployment:

![resourcegroup](https://cloud.githubusercontent.com/assets/4713713/16677033/29294610-4525-11e6-9949-af3fdcd604bd.PNG)

Any help or thoughts would be great I have had a good google and cannot figure out what this error means.

**Comment by aguilaaj** [comment]
Hi @justsayno - thanks for bringing this to our attention. See https://social.msdn.microsoft.com/Forums/en-US/02ecda9f-af03-42b4-b450-0bdaa24354d5/deployment-failed-cannot-find-user?forum=windowsazurewebsitespreview 

I'll send an update once a fix is rolled out.

**Comment by aguilaaj** [comment]
This issue should now be resolved, please reopen or open another issue if you continue to encounter problems. Thanks!
