### ISSUE TITLE
Command history doubling on device restart

### ISSUE THREAD

**Issue by marktayl1** [Azure/azure-iot-remote-monitoring#195]
I wrote a synthetic device using the C SDK starting with the tutorial.  Each time the device submits a DeviceInfo request, the existing command history doubles resulting in, eventually, errors processing the device as "too big".

It looks like the issue is with Infrastructure\businessLogic\DeviceLogic.cs – UpdateDeviceFromInfoPacketAsync() ln 258 - 262.  Merge method has issues with duplicating arrays.

Possible Fix:
// Merge device back to existing so we don't drop missing data
            if (existingDevice is JObject)
            {
                //Array objects are duplicating each time the deviceInfo is processed.
                existingDevice.Merge(device, new JsonMergeSettings
                {
                    // union array values together to avoid duplicates
                    MergeArrayHandling = MergeArrayHandling.Union
                });
            }

**Comment by jamesweb-ms** [comment]
We'll take a look, thanks for reporting

**Comment by kvish** [comment]
Fixed with change #217 - please reopen or create a new issue if you continue to encounter problems
