### ISSUE TITLE
Creating a connection string for IoT Hub's Event Hub

### ISSUE THREAD

**Issue by gustafsonk** [Azure/azure-iot-remote-monitoring#2]
So I created an IoT Hub today and I got pretty far with running the deployment script in my company's Azure subscription, but I ran into this issue.

The deployment script requires me to provide the IoT Hub’s Event Hub connection string. I’m able to see the name and endpoint for the IoT Hub’s Event Hub in the new Azure Portal, but I don’t see how I could create a connection string for it. Here’s the info I see:
Event Hub-compatible name: iotprod-hub
Event Hub-compatible endpoint: sb://iothub-ns-iotprod-hu-273-c880fcda84.servicebus.windows.net/

Here’s what the string looked like in our private subscription:
Endpoint=sb://dhubprpsbnamespace4.servicebus.windows.net/;SharedAccessKeyName=listen;SharedAccessKey=blahblahblah

I also don’t see an entry for iothub-ns-iotprod-hu-273-c880fcda84 in the old Azure Portal Service Bus page, but I’m assuming that’s how I could do it if it showed up there. I also tried using the Get-AzureSBNamespace command in Azure Powershell but it doesn’t show up there either.

Any ideas how I could create this string?

**Comment by jamesweb-ms** [comment]
Sorry, we have been busy working on the SuitePortal, that we didn't get time to cleanup the developer experience from our Private preview.  We will be checking in fixes for that this week.  In the meantime, here is a work around to deploy any changes you make:

Prep:
1) start azure powershell
2) add-azureaccount
3) Switch-AzureMode AzureResourceManager
4) cd \path\to\remotemonitoring
5) New-AzureResourceGroup -Name <rgname without spaces or dashes> -Location <EastUS | NorthEurope | EastAsia>
6) Determine your tenant (AAD) guid - you can get this from Get-AzureAccount, or from build local.

Note: step 5 is only needed if you haven't created resourcegroup yet

Deployment
7) New-AzureResourceGroupDeployment -ResourceGroupName <rg from step 5> -TemplateFile .\Common\Deployment\RemoteMonitoring.json -AADTenant <guid from step 6>

If step 7 succeeds, it will output the connection strings that build.cmd is prompting you for.  This will create all the resources the www.azureiotsuite.com creates, so please be aware of that and delete resources you don't need for development (like potentially cloudapp if you are using vs local debugging).

James

**Comment by jamesweb-ms** [comment]
Steve please add documentation for manual steps and then assign back to me to fix.

**Comment by gustafsonk** [comment]
Thanks. I was also able to solve it using this page as a reference to what the string is supposed to be. https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/run_end_to_end_tests.md 

All I had to do was go to the IoT Hub in the new Azure Portal, go into the Shared Access Policies section of the settings, select the iothubowner policy, and copied the Primary Key so that the string looked like Endpoint=sb://iothub-ns-iotprod-hu-273-c880fcda84.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=blahblahblah

Now the deployment script worked for everything except the end where it publishes code out to the worker roles. If I understand this new repository code correctly, I don't even need to deploy the worker roles anymore. I can just deploy the web project to an azure website and deploy the web job project as a web job, updating their settings of course. Is that correct?

**Comment by jamesweb-ms** [comment]
Please take a look at jamesweb-dev.  We are now using IotHub as input into the Stream analytics jobs.  You should be able to use "build local" and "build cloud [debug|release] <name>" for complete end to end deployments.

**Comment by jamesweb-ms** [comment]
This issue is now resolved in master
