### ISSUE TITLE
Environment name for German CLoud

### ISSUE THREAD

**Issue by gitralf** [Azure/azure-iot-remote-monitoring#204]
The environment name for the german cloud is AzureGermanCloud and not AzureGermanyCloud. Found in the docs/-section in cloud-deployment.md and in local-deployment.md

**Comment by handeadiguzel** [comment]
Thanks for reporting this issue. It's fixed with [commit](https://github.com/Azure/azure-iot-remote-monitoring/commit/6a449d6ff167f2db326a8047f1277c2b77066934)
