### ISSUE TITLE
build.cmd issue october intergration (new clone)

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#24]
I have just cloned the repository and I am trying to deploy the octoberintergration branch, however I receive the following error:

    Add-Type : Cannot bind parameter 'Path' to the target. Exception setting
    "Path": "Cannot find path 'C:\Users\Robin\Source\Repos\azure-iot-remote-monitor
    ing\packages\WindowsAzure.ServiceBus.3.0.1\lib\net45-full\Microsoft.ServiceBus.
    dll' because it does not exist."
    At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\De
    ploymentLib.ps1:705 char:16
    + ... -type -path ("{0}\..\..\packages\WindowsAzure.ServiceBus.3.0.1\lib\ne ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingExce
       ption
        + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Comm
       ands.AddTypeCommand

I believe this is because nuget has restored package WindowsAzure.ServiceBus.3.0.4 and would either involve changing DeploymentLib.ps1:705 to

    add-type -path ("{0}\..\..\packages\WindowsAzure.ServiceBus.3.0.4\lib\net45-full\Microsoft.ServiceBus.dll" -f $global:azurePath)

or setting nuget to specifically restore version 3.0.1

**Comment by networkfusion** [comment]
Also when choosing north Europe, the bing maps api resource fails to deploy (on successive re-running of build.cmd) with the failure:

    New-AzureResourceGroupDeployment : 20:11:15 - Resource
    Microsoft.BingMaps/mapApis 'surfacenet-map' failed with message 'An error
    occurred while processing the request.'
    At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\Pr
    epareIoTSample.ps1:80 char:11
    + $result = New-AzureResourceGroupDeployment -ResourceGroupName $resour ...
    +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroupDeploym
       ent], Exception
        + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou
       rceGroupDeploymentCommand

although I am guessing it is a region problem as I haven't tried deploying to anywhere else.

**Comment by jamesweb-ms** [comment]
add-type -path : That was old code.  Just needs to be removed as we load this in the library section now.  Will fix, thanks.

Maps: I think bing maps is in preview, and is only available in WestUS.  The template is hardcoded to create it in WestUS.  Did you change the template?

**Comment by networkfusion** [comment]
@jamesweb-ms No I haven't changed the template... Please try installing an instance in north Europe to see what I mean.

**Comment by jamesweb-ms** [comment]
Regarding Map error - we think this is a bing map issue.  We are following up with them.
Thanks for 2nd issue with single tenant was something I missed with my multitenants.  We'll merge this today.  I'll close once we know the bing maps issue.

**Comment by networkfusion** [comment]
Thanks.

Also note that your available locations list shows even when the question is not asked (i.e. the build script has been run previously and a location is already saved in the config file). which looks a little strange...

**Comment by jamesweb-ms** [comment]
Thanks, fixed it as well

**Comment by jamesweb-ms** [comment]
October-Integration is updated, please try this out again

**Comment by networkfusion** [comment]
Regarding the map error, (although I haven't tried it in the last couple of days) it seems that it is linked to using the map resource name previously. when using a new name for the resource group the map seems to provision correctly. To get around this I modified remotemonitoring.json to use
    "bingMapsName": "[concat(parameters('suiteName'), '2-map')]"
on a deployment I was having trouble with and I managed to deploy successfully (for the first time :) )
perhaps the bing maps name should have some random element as a work around...

**Comment by aguilaaj** [comment]
We just deployed a fix for Bing Maps being unable to handle previously used name, we're still testing, but feel free to try again.

**Comment by aguilaaj** [comment]
Marking this specific issue as closed as the Bing Maps API provisioning issue has been fixed and verified.
