### ISSUE TITLE
The viewbox of the map is calculated wrong

### ISSUE THREAD

**Issue by buzzfrog** [Azure/azure-iot-remote-monitoring#26]
It has to take in count both negative and positive numbers. A solution maybe is to remove the default coordinates centered around Seattle.

DeviceLogic.cs

/dag

**Comment by jamesweb-ms** [comment]
We have someone investigating

**Comment by jamesweb-ms** [comment]
This issue is now fixed in October integration.  Please feel free to try it out.

**Comment by jamesweb-ms** [comment]
This issue is now resolved in master
