### ISSUE TITLE
simulated device (october intergration)

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#31]
Hi,
are simulated devices currently working in the branch "October intergration"? When I add simulated devices (I haven't tried real devices yet either) the devices state stays as pending forever! Also the add device page suggests that I should follow the cooler sample instructions, please add the documentation or change the pages text.

**Comment by jamesweb-ms** [comment]
Yes, simulator not working is a known issue as a result of the webjob split.  We should have a fix out shortly for that issue.

We are also working on documentation.

**Comment by bmillerbma** [comment]
The following commit solves this problem by creating the devices with HUB_ENABLED_STATE = true.

https://github.com/bmillerbma/azure-iot-remote-monitoring/commit/0bf591275779c77af518c10aef1b550cbf617d3b

**Comment by jamesweb-ms** [comment]
Unfortunately that just hides the fact that there is no data.  That property is set the first time a DeviceInfo message is received.  Please try out October-Integration.  The original issue is now resolved there.
