### ISSUE TITLE
Plan internal1 can have no more than 2 resource(s)

### ISSUE THREAD

**Issue by luiey** [Azure/azure-iot-remote-monitoring#340]
Hi,

I'm building a remote monitoring solutions using Developer Command Prompt and the failed appear at creating Bing Maps console.

So, on Azure IoT Suite, my remote monitoring provision is failed where the failed one is the bing maps. In Azure IoT Suite, there is only 2 remote monitoring solutions.

Any thought?

**Comment by aguilaaj** [comment]
Hi @luiey - as described in our [FAQ](https://azure.microsoft.com/en-us/documentation/articles/iot-suite-faq/), you are correct - you can only provision with two Internal Transactions Level 1 Bing Maps for Enterprise plans. To create more than two remote monitoring solutions, you deploy either locally (see [local-deployment.md](https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/local-deployment.md)) or with a static map on www.azureiotsuite.com. 
Closing for now, please reopen or let us know if you have any additional questions.
