### ISSUE TITLE
Overwriting pricing/scaling configuration by re-deploying the template

### ISSUE THREAD

**Issue by konstantinmagg** [Azure/azure-iot-remote-monitoring#342]
Hi there,

your Template was a great place to start with Azure's IoT Hub. Thanks a lot for your effort. I'm not sure, if this is the right place for my issue. If there was a better one, please let me know.

Currently we are struggling with the pricing/scaling configuration of the Azure Resources.

### What I did?
- First we deployed the remote-monitoring template by running **build.cmd**.
- Then we configured the tiers and scaling plans for our resources as recommended here: https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/configure-preconfigured-demo.md#configuring-azure-iot-suite-preconfigured-solutions-for-demo-purposes
- Then we re-deploy the solution, again by running **build.cmd**.

### What did I expect?
I expected, the re-deploy would not affect our configuration for tiers and scaling. At least that is, what I got from these [docs](https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/configure-preconfigured-demo.md#configuring-azure-iot-suite-preconfigured-solutions-for-demo-purposes):

> If you redeploy your solution from the command line, we respect the scale changes you’ve made and **will not overwrite these** changes with the default template.

### What actually happened
The re-deploy reset our config to the default values.

**Is there a possibility, that we get the re-deploy wrong? Or is the re-deploy actually overwriting tiers and pricing/scaling configurations?**

Any hint is welcome. Thanks for your support.

**Comment by aguilaaj** [comment]
Thanks for reporting, @konstantinmagg - we're taking a look.

**Comment by jtanner-msft** [comment]
Hi @konstantinmagg,

  Thank you for your question.  I wanted to let you know that I have been able to repro what you observed myself.  We will look into why this behavior is happening, but for the time being anytime you do re-deploy your IoT Suite please go and follow the checklist to adjust the resources to the lower level again.

Thanks,

**Comment by rraomsft** [comment]
@konstantinmagg Thank you for reporting this issue. This issue should be fixed with this [commit](https://github.com/Azure/azure-iot-remote-monitoring/commit/b0f1735494dbc9e1ed2057d178886f7f47660ea5).

**Comment by jtanner-msft** [comment]
Hi @konstantinmagg,

  As we believe this issue should be resolved with the commit @rraomsft has made, I’m closing this issue.  If you do continue to see the problem when using that commit please feel free to re-activate the issue.

Thanks,

**Comment by konstantinmagg** [comment]
Thanks for your quick reaction! I'll have a look ;)
