### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by monteil** [Azure/azure-iot-remote-monitoring#38]
Hello,

This is more a question than an issue: Does the remote monitoring application is designed to supports multi-tenancy? In other terms, does it implement data isolation (such as tables with one partition key per tenant or blob containers per tenant)?
If this is not supported yet, are there any future plans to integrate multi-tenancy in the remote monitoring solution?

Thank you for your help.

Stephane

**Comment by aguilaaj** [comment]
Hi Stephane - this is not currently designed for multi-tenancy nor do we have plans to add that functionality at this time. However, there is nothing stopping a customer from adding multi-tenancy and the current design is meant to be built on top of.

**Comment by monteil** [comment]
Hi Ariel,
Thanks for your feedback. I might work on this evolution in the near future.
Stephane
