### ISSUE TITLE
Issue at Local deployment and debugging

### ISSUE THREAD

**Issue by toupilsner** [Azure/azure-iot-remote-monitoring#394]
I am trying to deploy solution to local using build.cmd local, but I always get the same error:

_> _New-AzureRmResourceGroup : Invalid tag format. Expect @{Name = "tagName"} or @{Name = "tagName"; Value = "tagValue"}
> At \azure-iot-remote-monitoring-master\azure-iot-remote-monitoring-master\Common\Deployment\De
> ploymentLib.ps1:182 char:16
> + ...      return New-AzureRmResourceGroup -Name $name -Location $global:Al ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroup], ArgumentException
>     + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupCmd
>    let__

The problem is here, but I do not know which information is correct: 

```
if ($resourceGroup -eq $null)
    {
        return New-AzureRmResourceGroup -Name $name -Location $global:AllocationRegion -Tag @{"IoTSuiteType" = $type ; "IoTSuiteVersion" = $global:version ; "IoTSuiteState" = "Created"}
    }
```

OS: Windows 10
Powershell:  5
Azure-SDK: .NET SDK\v2.9

**Comment by jtanner-msft** [comment]
Hi @toupilsner,
  Just a few initial questions for you:
  What version of Windows AzurePowerShell are you using?
  If you instead first try a cloud command line deployment does that work correctly?
  <or>
  If you create an IoT Suite thru the azureiotsuite.com portal, does that work correctly for you?
Thanks,

**Comment by toupilsner** [comment]
The problem was that "Windows AzurePowerShell" was using an outdated version (1.4). When I upgraded AzurePowerShell it works. Thanks!
