### ISSUE TITLE
Unit test failure when not using US locale

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#396]
Please consider using UTC and ISO formats within pseudo JSON?!

Assert.Equal() Failure
Expected: 2016-05-07T00:00:00.0000000
Actual: 2016-07-05T00:00:00.0000000
Stack Trace:
at Microsoft.Azure.Devices.Applications.RemoteMonitoring.UnitTests.Infrastructure.AlertsRepositoryTests.<LoadLatestAlertHistoryAsyncTest>d__5.MoveNext() in C:\agent\_work\1\s\UnitTests\Infrastructure\AlertsRepositoryTests.cs:line 64

**Comment by networkfusion** [comment]
As a work around, the following will work:

Assert.Equal(alertsList.First().Timestamp, DateTime.Parse(minTime.ToString(), new CultureInfo("en-US", false)));

**Comment by networkfusion** [comment]
This is also the case with the following unit test: LoadLatestDeviceTelemetryAsyncTest() but fails in Assert.NotEmpty(). I have not yet found the reason or a workaround.

**Comment by networkfusion** [comment]
The following changes allow the test to run successfully:

`        public async void LoadLatestDeviceTelemetryAsyncTest()
        {
            var year = 2016;
            var month = 7;
            var date = 5;
            var minTime = new DateTime(year, month, date);

            var blobReader = new Mock<IBlobStorageReader>();
            var blobData =
                "deviceid,temperature,humidity,externaltemperature,eventprocessedutctime,partitionid,eventenqueuedutctime,IoTHub" +
                Environment.NewLine +
                "test1,34.200411299709423,32.2233033525866,,2016-08-04T23:07:14.2549606Z,3," + minTime.ToString("o") + ",Record";
            var stream = new MemoryStream(Encoding.UTF8.GetBytes(blobData));
            var blobContents = new BlobContents {Data = stream, LastModifiedTime = DateTime.UtcNow};
            var blobContentIterable = new List<BlobContents>();
            blobContentIterable.Add(blobContents);

            blobReader.Setup(x => x.GetEnumerator()).Returns(blobContentIterable.GetEnumerator());
            _blobStorageClientMock.Setup(x => x.GetReader(It.IsNotNull<string>(), It.IsAny<DateTime?>()))
                .ReturnsAsync(blobReader.Object);
            var telemetryList = await deviceTelemetryRepository.LoadLatestDeviceTelemetryAsync("test1", null, minTime);
            Assert.NotNull(telemetryList);
            Assert.NotEmpty(telemetryList);
            Assert.Equal(telemetryList.First().DeviceId, "test1");
            Assert.Equal(telemetryList.First().Timestamp, minTime);
        }`

**Comment by rraomsft** [comment]
@networkfusion Thanks for reporting this. I've incorporated your suggested fixes in the unit tests.

**Comment by networkfusion** [comment]
your welcome.
