### ISSUE TITLE
java sdk for remote monitoring preconfigured solution

### ISSUE THREAD

**Issue by sajanrai** [Azure/azure-iot-remote-monitoring#400]
I was trying to connect a device to the remote monitoring preconfigured solution. i went through the tutorial suggested at https://azure.microsoft.com/en-us/documentation/articles/iot-suite-connecting-devices-linux/ I found different scenarios to implement it. But the actual problem is, I was trying to implement using java. Do we have a java sdk for remote monitoring preconfigured solution? 
Thanks in advance.

**Comment by rraomsft** [comment]
@sajanrai While we don't have a IoT Suite guide for Java, you should be able to use the [Java SDK](https://github.com/Azure/azure-iot-sdks/tree/master/java/device) however to get your device connected to Remote Monitoring.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
