### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-iot-remote-monitoring#404]
I am having same problem as #161 but on my latest cloud deployment. I have not had this before and I have deployed many times on local and cloud. I have waited for nearly 4 hours and tried again to log in but I keep getting directed to sign in page.

thanks

**Comment by networkfusion** [comment]
There seems to be some problems occurring with deployments at the moment (see #403) but you can try a couple of things:

Login to http://manage.windowsazure.com and check that <yourdeploymentname>App exists. If it does
Go into the app config and copy the client id for later. Login to portal.azure.com and check that your web jobs have the correct client id in their properties. and/or update the client id in your deployment config

if it doesn't, you have 2 options, create it manually or delete it (and the resource group in portal.azure.com) then redeploy from scratch.



Hope all that makes sense...

**Comment by basimolimajeed** [comment]
thanks networkfusion. At the end I had to redeploy and this time it worked. The client id was different as you said. I also changed region just in case.
