### ISSUE TITLE
Session expired after one hour

### ISSUE THREAD

**Issue by nmaroine** [Azure/azure-iot-remote-monitoring#409]
hi all,
we are trying to expose Azure iot Remote monitoring solution on an Exposition, but the problem is that the session expire after 1 hour, there is any solution to extend the session life time ?

or can we disable the authentification?
thank you in advance

**Comment by networkfusion** [comment]
Please explain further... What is an exposition?

**Comment by nmaroine** [comment]
@networkfusion  in a show room we have a board with the Dashboard on it, the problem is that the session expire and we have to re log in manual, my question is , there is a way to set a long timer on the session or any way to remove the authentication part ?

**Comment by networkfusion** [comment]
Although I probably don't know what I am talking about, it might be possible to use 

`usetokenlifetime`

https://msdn.microsoft.com/en-us/library/microsoft.owin.security.openidconnect.openidconnectauthenticationoptions.usetokenlifetime(v=vs.113).aspx#P:Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions.UseTokenLifetime to extend the timeout period

in https://github.com/Azure/azure-iot-remote-monitoring/blob/master/DeviceAdministration/Web/App_Start/Startup.Auth.cs 

However the token would need to be refreshed on a regular basis to still be valid.

You could also remove the authentication by modifying https://github.com/Azure/azure-iot-remote-monitoring/blob/master/DeviceAdministration/Web/Controllers/AccountController.cs however I would not recommend that!

or you could adjust all of the inbuilt authentication mechanisms with a different one.
