### ISSUE TITLE
'Get-AzureEnvironment' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by paulmon** [Azure/azure-iot-remote-monitoring#410]
I'm trying to follow the directions for "local deployment and debugging" and I'm seeing this output when I run "build.cmd local" on two different machines.

Get-AzureEnvironment : The term 'Get-AzureEnvironment' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At E:\github\azure-iot-remote-monitoring\Common\Deployment\PrepareIoTSample.ps1:14 char:14
+         if ((Get-AzureEnvironment AzureCloud) -eq $null)
+              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureEnvironment:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by networkfusion** [comment]
Which version of Azure Powershell are you using?
and Azure SDK version?

The command does exist (https://docs.microsoft.com/en-us/powershell/servicemanagement/azure.profile/v3.4.0/get-azureenvironment)

**Comment by paulmon** [comment]
I didn't have the Azure powershell module, because the directions didn't say I needed it here: https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/dev-setup.md or maybe this page has changed since https://docs.microsoft.com/en-us/powershell/azureps-cmdlets-docs/ AzureRM has Get-AzureRMEnvironment.

Also, I had to specify -AllowClobber with Install-Module because Azure and AzureRM both have APIs with exactly the same name.

**Comment by networkfusion** [comment]
Cool, if that got you up and running I suggest you create a pull request with how the doc can be improved... Btw I am only a user  / contributer and support seems to be a bit sporadic...

**Comment by arvindsinghagra** [comment]
I am also facing same issue. @paulmon Can you please point to me how to resolve that.

**Comment by paulmon** [comment]
I ended up remove the azure powershell cmdlets and reinstalling because it looked like I had version issues.  I don't know if this is still the correct version, but it was still working for me recently

#remove all azure modules
$m = Get-Module azure* -ListAvailable
$m | %{Uninstall-Module -Name $_.Name -RequiredVersion $_.Version }
 
# listing azure modules now should show nothing
Get-Module azure* -ListAvailable
 
# not sure if both of these are required.  I believe Azure pulls in AzureRM as a depenency
Install-Module -Name Azure -Repository PSGallery -RequiredVersion 3.7.0 -AllowClobber
Install-Module -Name AzureRM -Repository PSGallery -RequiredVersion 3.7.0 -AllowClobber

**Comment by arvindsinghagra** [comment]
Thanks  @paulmon looks like for me also it was version problem. i removed all the azure* related stuff
from 
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
%SYSTEMROOT%\Program Files\WindowsPowerShell\Modules
and then install again. After  that got an issue with azurestorage for i installed using -AllowClobber option.
