### ISSUE TITLE
cloud deployment - creation of AD app failed, implicit read only

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/azure-iot-remote-monitoring#411]
I deployed the remote monitoring solution as described in https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/cloud-deployment.md
All Azure services got installed but my user has no administrative priviliges, it is "IMPLICIT READ-ONLY". Thus, I am not able to use the schedule jobs. 
I have no issue if I deploy it via portal.

**Comment by networkfusion** [comment]
You need to go to the AAD part of the portal find the app (filter by applications your company owns) and add the user and assign the user appropriate permissions. This used to have to be done in the classic portal, I am not sure if it can now be done in the main portal...

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
