### ISSUE TITLE
Bing Maps V7 control and SOAP Web Services deprecation on June 30

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#413]
Currently when multiple devices are added to an area it is hard to distinguish what is going on. this could be solved by using a heat/cluster map.

**Comment by networkfusion** [comment]
I would also suggest moving to the V8 API (https://social.technet.microsoft.com/wiki/contents/articles/34563.bing-maps-v7-to-v8-migration-guide.aspx) as a lot of the currently used modules etc. in MapPane.js are depreciated...

**Comment by networkfusion** [comment]
here is my code for the V8 api...

MapPane.js:
`
IoTApp.createModule('IoTApp.MapPane', (function () {
    "use strict";

    var self = this;
    var mapApiKey = null;
    var map, clusterLayer;
    var pinInfobox;
    var boundsSet = false;

    var init = function () {
        $.ajaxSetup({ cache: false });
        getMapKey();
    }

    var getMapKey = function () {
        $.get('/api/v1/telemetry/mapApiKey', {}, function (response) {
            self.mapApiKey = response;
            startMap();
        });
    }

    var startMap = function () {
        Microsoft.Maps.loadModule('Microsoft.Maps.Clustering', { callback: finishMap });
    };


    var finishMap = function () {

        var options = {
            credentials: self.mapApiKey,
            mapTypeId: Microsoft.Maps.MapTypeId.lightCanvas,
            enableClickableLogo: false,
            allowHidingLabelsOfRoad: true
        };

        // Initialize the map
        self.map = new Microsoft.Maps.Map('#deviceMap', options);

        self.map.setView({ labelOverlay: Microsoft.Maps.LabelOverlay.hidden });

        // Hide the infobox when the map is moved.
        Microsoft.Maps.Events.addHandler(self.map, 'viewchange', hideInfobox);
    }

    var onMapPinClicked = function (e) {
        IoTApp.Dashboard.DashboardDevicePane.setSelectedDevice(e.target.metadata.id);
        displayInfobox(e);
    }

    var displayInfobox = function (e) {
        // Create the infobox for the pushpin
        if (self.pinInfobox != null) {
            hideInfobox(null);
        }

        var id = e.target.metadata.id;
        //var width = (id.length * 7) + 35;
        //var horizOffset = -(width / 2);
        self.pinInfobox = new Microsoft.Maps.Infobox(e.target.getLocation(),
            {
                title: id,
                visible: true,
                //offset: new Microsoft.Maps.Point(horizOffset, 35)
            });

        self.pinInfobox.setMap(self.map);
    }

    var hideInfobox = function (e) {
        if (self.pinInfobox != null) {
            self.pinInfobox.setOptions({ visible: false });
            self.pinInfobox.setMap(null);
            self.pinInfobox = null;
        }
    }

    var setDeviceLocationData = function setDeviceLocationData(minLatitude, minLongitude, maxLatitude, maxLongitude, deviceLocations) {
        var i;
        var loc;
        var mapOptions;
        var pin;
        var pinOptions;
        var pins = [];

        if (!self.map) {
            return;
        }

        if (!boundsSet) {
            boundsSet = true;

            mapOptions = self.map.getOptions();
            mapOptions.bounds =
                Microsoft.Maps.LocationRect.fromCorners(
                    new Microsoft.Maps.Location(maxLatitude, minLongitude),
                    new Microsoft.Maps.Location(minLatitude, maxLongitude));
            self.map.setView(mapOptions);
        }

        self.map.entities.clear();
        if (deviceLocations) {
            for (i = 0 ; i < deviceLocations.length; ++i) {
                loc = new Microsoft.Maps.Location(deviceLocations[i].latitude, deviceLocations[i].longitude);

                pinOptions = {
                    //anchor: new Microsoft.Maps.Point(0, 0),
                    //height: 17,
                    //width: 17
                };

                switch (deviceLocations[i].status) {
                    case 1:
                        //pinOptions.icon = resources.cautionStatusIcon;
                        pinOptions.color = 'orange';
                        break;

                    case 2:
                        //pinOptions.icon = resources.criticalStatusIcon;
                        pinOptions.color = 'red';
                        break;

                    default:
                        //pinOptions.icon = resources.allClearStatusIcon;
                        pinOptions.color = 'green';
                        break;
                }

                pin = new Microsoft.Maps.Pushpin(loc, pinOptions);

                pin.metadata = {
                    id: deviceLocations[i].deviceId
                };

                Microsoft.Maps.Events.addHandler(pin, 'click', onMapPinClicked);
                self.map.entities.push(pin);
                //pins.push(pin);

            }
            //self.clusterLayer = new Microsoft.Maps.ClusterLayer(pins);
            //self.map.layers.insert(clusterLayer);

        }
    }

    return {
        init: init,
        setDeviceLocationData: setDeviceLocationData
    }
}), [jQuery, resources]);

$(function () {
    "use strict";

    IoTApp.MapPane.init();
});
`

index.cs line 39 changed to:
`<script charset="UTF-8" type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol"></script>`

I still have the following issues though:
pushpin icons display too large (work around use the default pushpins with custom colour)
cannot get clustering to work (code commented out)

I have spent a day on this and have no more time with my limited JS skills... if anyone can help get the last problems ironed out it would be helpful. TIA

**Comment by networkfusion** [comment]
30th June is getting rather close, will the map continue to work after that?!

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
