### ISSUE TITLE
Consider adding autorefresh to commands/methods

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#414]
When issuing a command/method, you need to refresh the page to decipher whether a command/method has completed successfully. consider refreshing the page (or table) automatically periodically so that it is obvious to whether a command/method has completed or failed.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
