### ISSUE TITLE
Dynamic telemetry

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#420]
In the last few months it seems that a bug has been introduced when not using the default "Cooler Demo" telemetry scheme.

for example, if I send: {"DeviceId": "12345","PressureMbar":1030.6099999999999} I would expect the graph to display the PressureMbar value, however at the moment it is displaying the following:

Deviceid, Partitionid, PressureMbar.

Because my DeviceId is a large number taken from a UUID chip, this number is very large and means that no telemetry is being displayed.

Perhaps it has something to do with the move away from the dynamic keyword?

**Comment by networkfusion** [comment]
As an update, if I prefix the device id with characters, e.g. "SN-12345", device ID is no longer shown, however partitionid is...

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
