### ISSUE TITLE
hostname azurecloud is not available

### ISSUE THREAD

**Issue by a-karnik** [Azure/azure-iot-remote-monitoring#421]
Hi,

![azurecloud is not valid](https://cloud.githubusercontent.com/assets/8175050/25416278/996a1202-2a02-11e7-9138-eb6718e8c740.png)

I am using VS 2013. Trying to deploy the IoT solution to Azure Cloud.
I ran below command

build.cmd cloud debug AzureCloud

It gives me below error.

hostname azurecloud is not available

I have attached screen shot. Can you please help?

Thanks

**Comment by joyhui** [comment]
It means the name "AzureCloud" is taken. You should give a unique string as your solution name, since it will be used as a DNS for your website.  If the name is token by someone else, you have to give a different name.  

Here is the command line:
build.cmd cloud [debug | release] <deploymentname>

You can try:
build.cmd cloud debug KarnikCloud

Guideline:
https://github.com/xzsheng/azure-iot-remote-monitoring/blob/limliu/Docs/cloud-deployment.md

**Comment by a-karnik** [comment]
Thanks for the reply Hui. I will try that tonight.

Ashish Karnik

**Comment by a-karnik** [comment]
Hui, I went ahead and now got this error...

unable to create unique name for resource karnikcloud for url azure-devices.net
Error comes from line 293 in DeploymentLib.ps1.

Can you please help?

Thanks
Ashish

**Comment by zhang-hua** [comment]
@a-karnik, the hostname 'karnikcloud.azure-devices.net' is used by the IoTHub resource karnikcloud. Looks like it has already been taken by someone else. Since these resources are globally unique, please add some random numbers after the name so that it has not possible conflicts.

**Comment by a-karnik** [comment]
Thanks Zhang-hua. I tried changing to KarnikCloud14141 and KarnikCloudReallyLongName but get same exception.
I am sorry; I am new to Powershell and Azure world. 
Can you please help?

Thanks
Ashish

**Comment by a-karnik** [comment]
Zhang-hua, FYI, When I log in my Azure Portal account, I see both under "All Resource". Does it mean that the deployment was successful?

Thanks
Ashish

**Comment by zhang-hua** [comment]
@a-karnik , all of the Azure resources of remote monitoring solution will be deployed into one resource group with the same name. And if you want to remove the deployed solution, just delete the resource group so that Azure Resource Manager will delete everything that you just deployed.

**Comment by zhang-hua** [comment]
@a-karnik , please also ping the DNS name locally on your machine to see if it is resolvable. Some ISP or your network service provider may reply the DNS name resolution request which misled the PowerShell script.

**Comment by a-karnik** [comment]
Thanks Zhang-Hua, please check the attached snap shot of results when I ran above command from PowerShell. Does this help?

Thanks
Ashish

![dnspowershell screenshot](https://cloud.githubusercontent.com/assets/8175050/25511797/cb59a97a-2b8e-11e7-9f92-8081e89720f7.jpg)

**Comment by zhang-hua** [comment]
@a-karnik , I pushed a PR to fix this local DNS resolution issue at [422](https://github.com/Azure/azure-iot-remote-monitoring/pull/422). It  has passed in my tests. please try it and tell us your feedback. Thanks! 

+@joyhui

**Comment by a-karnik** [comment]
Thanks Zhang-Hua, I did copy new files in my folder and re ran below command.

build.cmd cloud debug karnikClud2

I got attached exception -  "The Term 'Resolve-DnsName' is not recognized as the name of cmdlet....".

Can you please take a look?

Thanks
Ashish Karnik
![resolve-dnsname](https://cloud.githubusercontent.com/assets/8175050/25552502/eadb49ac-2c60-11e7-9faa-ca7e57791b5f.png)

**Comment by networkfusion** [comment]
This fix would only work on windows 8 and above (I guess you are using windows 7...) you could try the fix using a later OS or try the change using a command such as:[System.Net.Dns]::GetHostAddresses("www.google.com")

**Comment by zhang-hua** [comment]
@a-karnik , just as @networkfusion said, this command works only for Windows Server 2012 R2 and Windows 8.1. It is a DNS client tool to support more options (e.g. DNS server) than [System.Net.Dns]::GetHostAddresses().  Here is a document [link](https://technet.microsoft.com/en-us/library/jj590781(v=wps.630).aspx) FYI. What's your OS version and Powershell version(use $PSVersionTable to get it)?

**Comment by zhang-hua** [comment]
@a-karnik , please have another try with the new branch [fix_issue_421](https://github.com/Azure/azure-iot-remote-monitoring/tree/fix_issue_421). I add some work around logic in the Powershell script to detect DNS issue you have. Hope this can help you! :-)

**Comment by a-karnik** [comment]
Thanks for your help Zhang-Hua. I downloaded new project and I think I went futher in deploying the project in my Azure Account; came across attached issue. Can you please take a look?

I need one more help from you. 
Can you please tell me how to debug this solution on my local box? Can I do it without deploying in Azure Cloud? Appreciate your help.

Thanks
Ashish Karnik
![content-type header must be modified](https://cloud.githubusercontent.com/assets/8175050/26021859/0cb60a3e-375c-11e7-804d-77e03da8c5bf.png)

**Comment by zhang-hua** [comment]
@a-karnik  What's your OS version and Powershell version(use $PSVersionTable to get it)? please also try this command and let me know the output。

**Comment by a-karnik** [comment]
Hi Zhang Hua, please check the PS Version.
I am using Windows 7.

Thanks
Ashish

**Comment by v-limliu** [comment]
@a-karnik      
what the   powershell version  you use,  you can use this command  "$PSVersionTable"  to see that 
   ![image](https://cloud.githubusercontent.com/assets/26808087/26184243/41bfa056-3bb6-11e7-8d08-b7d4798773d9.png)

**Comment by a-karnik** [comment]
Hi all, I was able to deploy the solution with windows 10. Thank you all
for you help; I really appreciate it.

Thanks
Ashish Karnik

**Comment by zhang-hua** [comment]
@a-karnik great news! So are you using the branch  [fix_issue_421](https://github.com/Azure/azure-iot-remote-monitoring/tree/fix_issue_421) which aims to target DNS problem? or you are using master branch without any problem?

**Comment by a-karnik** [comment]
His Zhang, we used master branch and that worked fine for us.

Thanks
Ashish

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
