### ISSUE TITLE
New Device placed in Running State rather than Pending State

### ISSUE THREAD

**Issue by kwaynesnyder** [Azure/azure-iot-remote-monitoring#424]
When I create a new custom device, it is shown in the Devices window as Running instead of Pending. My understanding is that the hubstate should be Null, and the App value should be Pending until the device actually connects and sends the device information... This is going to cause me to have to re-write a bunch of class materials ( which came from Microsoft) for a session that begins in 2 weeks....

**Comment by networkfusion** [comment]
This is to do with the change to using mqtt and device twins. It seems to ignore the start up message entirely... I have noticed this as well...

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
