### ISSUE TITLE
Error when redeploy solution

### ISSUE THREAD

**Issue by iamgyt** [Azure/azure-iot-remote-monitoring#432]
When redeploy a solution, it reports error. I did a quick check, the latest EventHub APIVersion doesn't have this property anymore: ehSku=$($**eventhubSku.Properties.MessagingSku**)

Error Message: 

New-AzureRmResourceGroupDeployment : 3:14:30 PM - Error: Code=InvalidDeploymentParameterValue; Message=The value
of deployment parameter 'ehSku' is null. Please specify the value or use the parameter reference. See
https://aka.ms/arm-deploy/#parameter-file for details.
At C:\000Projects\azure-iot-remote-monitoring-master\Common\Deployment\PrepareIoTSample.ps1:212 char:11
+ $result = New-AzureRmResourceGroupDeployment -ResourceGroupName $reso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGrou
   pDeploymentCmdlet

**Comment by malindaA** [comment]
Having Same Issue.Did you find any solution?

**Comment by malindaA** [comment]
I fixed this by assigning "ehsku" to 1  mannualy in PrepareIoTSample.ps1

    if (ResourceObjectExists $suitename $eventhubName Microsoft.Eventhub/namespaces)
    {
        $eventhubSku = GetResourceObject $suitename $eventhubName Microsoft.Eventhub/namespaces
        $params += @{ehSku=1}

**Comment by iamgyt** [comment]
you can fix it like that @malindaA , but actually the EventHub template has been changed, so it would be the template file itself need to be fixed, EventHub doesn't have a property named MessagingSku anymore.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
