### ISSUE TITLE
ConfigurationProvider should be SingleInstance in Web project?

### ISSUE THREAD

**Issue by lairship** [Azure/azure-iot-remote-monitoring#433]
When I enable log, I found many many log such as:

> _Getting "device.StorageConnectionString" from ServiceRuntime: FAIL.
> Getting "device.StorageConnectionString" from ConfigurationManager: PASS._

So, I debug Web project, then found below code:
`            builder.RegisterType<ConfigurationProvider>().As<IConfigurationProvider>();`
Bug, in EventProcessor WebJob and Simulator Webjob, Register ConfigurationProvider as:
`            builder.RegisterType<ConfigurationProvider>().As<IConfigurationProvider>().SingleInstance();`
I think that it is missed `.SingleInstance` in Web project

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
