### ISSUE TITLE
Disable a rule on the web dashboard will bring back to the first page of rules list panel

### ISSUE THREAD

**Issue by chris-han** [Azure/azure-iot-remote-monitoring#437]
Nav to the ‘Rules' section of the web dashboard
click page 2 or 3 at the bottom of Rules list panel
select any active rule, and click 'Disable Rule' button on the property panel
Rules list panel will be set to page 1

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
