### ISSUE TITLE
Sending DeviceInfo message to the IotHub doesn’t create the device in remote monitoring solution

### ISSUE THREAD

**Issue by bhuvanalakshmi** [Azure/azure-iot-remote-monitoring#446]
Created a device in IotHub (of the remote monitoring solution) and sent DeviceInfo Message to the device using the iothub device client
```
iothub_registry_manager = IoTHubRegistryManager(connection_string)
iothub_registry_manager.create_device(device_id, "", "", IoTHubRegistryManagerAuthMethod.SHARED_PRIVATE_KEY)
iothub_client.send_event_async(message, send_confirmation_callback, message_id)
```
 
DeviceInfo Message
```
{
   "DeviceProperties":{
      "DeviceID":"xxxx",
      "HubEnabledState":true
   },
   "Telemetry":[
      {
         "Name":"Temperature",
         "DisplayName":"Temperature",
         "Type":"double"
      },
      {
         "Name":"Humidity",
         "DisplayName":"Humidity",
         "Type":"double"
      }
   ],
   "Version":"1.0",
   "ObjectType":"DeviceInfo"
}
```
I don’t see the device in the Remote Monitoring devices UI. Device is present in the IOTHub but not in the Cosmos DB. If I add the device manually using the Remote Monitoring Iot Suite devices UI, then the device is present in the IOTHUb as well as Cosmos DB.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
