### ISSUE TITLE
 Unable to add rules for new telemetry fields added through the DeviceInfo message

### ISSUE THREAD

**Issue by bhuvanalakshmi** [Azure/azure-iot-remote-monitoring#448]
Unable to add rules for new telemetry fields added through the DeviceInfo message. Currently only temperature and humidity is listed.
<img width="666" alt="azure-rules" src="https://user-images.githubusercontent.com/2466561/30830356-a77f012c-a1f8-11e7-808e-80342ff572b9.png">

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
