### ISSUE TITLE
Issue while deploying seperate Web job sending sensor data instead of Telemetry Data

### ISSUE THREAD

**Issue by AnaghaPirangute** [Azure/azure-iot-remote-monitoring#450]
Hi Team

1) We have been trying to deploy one more web job to send the actual sensor data to IOT hub instead of the telemetry data in simulator.webjob.
To deploy this web job as a part of usual deployment i.e. using command "Build.cmd cloud release Mydeployment" I have added the web job as a part of whole solution but no luck. I am unable to deploy the solution. 
Can you get me guide lines to add one more web job which can get deployed as a part of the solution.

2) I have as well tried deploying the web job from my visual studio separately. The Job runs good in VS but once deployed on Azure, its unable to connect the IOT Hub and fails. Can you please provide guidelines on deploying this too and necessary config settings the Web Job should have.

Thanks,
Anagha

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
