### ISSUE TITLE
build local problem

### ISSUE THREAD

**Issue by stefanwil** [Azure/azure-iot-remote-monitoring#451]
When running 
build local
at Developer Prompt for VS 2017 I get message

![issue build](https://user-images.githubusercontent.com/16291295/31125150-9b4c2aba-a847-11e7-90a2-26fcb1f57a01.png)

What need to be updated to new version? Do you have an idea?

**Comment by itague** [comment]
You need to update Azure Powershell modules.
Simply run a powershell prompt and type the command: **Install-Module Azure -Force AllowClobber**
Last version is 4.4.0

Good luck!

**Comment by psureshk1** [comment]
Hello, I tried installing Azure (Install-Module Azure -Force AllowClobber) on power-shell as Administrator while to posted 'positionalParameter not found'

so i tried a couple of things but still nothing worked out, it still says i need to update


Kindly let me know if anything else is possible
![untitled](https://user-images.githubusercontent.com/16074364/32867654-485acdea-ca23-11e7-9443-bf3237f1ebcf.png)

**Comment by magixus** [comment]
# powsershell v4.0+ as Administrator `(in my case 5.1+)`
```powershell
Install-Module -Name Azure -Repository PSGallery -RequiredVersion 4.2.1 -AllowClobber
Install-Module -Name AzureRM -Repository PSGallery -RequiredVersion 4.2.1 -AllowClobber
```

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
