### ISSUE TITLE
scheduling jobs from webapp treats all parameters as string.

### ISSUE THREAD

**Issue by ArsalanSaleemGhuman** [Azure/azure-iot-remote-monitoring#452]
When the method with integer parameter is called by selecting methods then the integer parameter passed as an integer.

The problem i faced was that i was Unable to schedule ChangeLightStatus() Method on two devices using Job Scheduling. When job is used to call the same method the integer parameter is passed as a string due to which the serializer reports data type errors.

The remote monitoring job scheduling part needs some fixes here.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
