### ISSUE TITLE
Rules using Boolean data aren't triggering

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-iot-remote-monitoring#455]
I'm trying to set up a rule for when a Boolean data point ("isSoilDry") is true.

![screen shot 2018-02-01 at 11 38 07 am](https://user-images.githubusercontent.com/2644648/35699304-81584c0e-0744-11e8-9d83-67d551f4dc7c.png)
I've tried the following conditions when creating the rule:

isSoilDry = true
isSoilDry = 1
isSoilDry > 0

but nothing is triggering it as you can see by the lack of "last triggered" data on the right
![screen shot 2018-02-01 at 11 38 17 am](https://user-images.githubusercontent.com/2644648/35699324-8d20abee-0744-11e8-8b00-ffaba28943a7.png)

I noticed that data is coming in, though. Here you see it is false with a value of 0 in the graph. (It has been true before and the rule didn't fire)
![screen shot 2018-02-01 at 11 38 41 am](https://user-images.githubusercontent.com/2644648/35699359-a98d327a-0744-11e8-92e6-0a4d9591194e.png)

Any thoughts?

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
