### ISSUE TITLE
web portal stuck in infinite redirect

### ISSUE THREAD

**Issue by pankajisgarg** [Azure/azure-iot-remote-monitoring#457]
On leaving portal up over weekend, on refresh portal was stuck in infinite redirect to auth and home page.
And sometimes in different path redirects to https://<RM>.azurewebsites.net/null with no content.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
