### ISSUE TITLE
Telemetry shows "no data available"

### ISSUE THREAD

**Issue by EricMcio** [Azure/azure-iot-remote-monitoring#462]
Hi all,

yesterday I deployed the IoT Remote Monitoring solution. I added an MxDevice IoT DevKit. 
Everything was running smoothly.

After logging in today, I can not see any Telemetry data anymore. I only get "no data available" even with the default simulated devices being active. 
Using VS Code and D2C monitoring I can see that the MxDevice sends data to the IoT Hub. 

What can I do? In fact, this was my first Azure Test so I am a bit lost.

Thank you in advance.

Edit: I just noticed that Analytics and Alerts also show "No data available".

**Comment by shenhuaz** [comment]
maybe your streamingjobs on portal not started

**Comment by EricMcio** [comment]
Thank you, @shenhuaz . 
The issue can no longer be tracked down. I had to redeploy the solution to ensure a timely Demonstration. As it can not be reproduced I'll close the ticket.
