### ISSUE TITLE
RMv2 shows "Version 1.0.0" under settings flyout.

### ISSUE THREAD

**Issue by peterfelts** [Azure/azure-iot-remote-monitoring#463]
![image](https://user-images.githubusercontent.com/5828480/41130212-899061de-6a6a-11e8-93b5-b3e6eb809c86.png)

In RMv2's Settings flyout, the version shown is incorrect. Also, the releasenotes links to RMv1 notes. 

Repro steps:
1. Create new RM solution
2. Click on Settings button

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
