### ISSUE TITLE
Incorrect deployment of Remote Monitoring solution

### ISSUE THREAD

**Issue by andrepodnozov** [Azure/azure-iot-remote-monitoring#466]
I just deployed Remote Monitoring solution from www.azureiotsolutions.com
After it finished deployment, I opened the solution accelerator link and got the following message:
"The dashboard configuration is missing. Verify content of webui-config.js"
Please fix this. 
Thanks

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
