### ISSUE TITLE
Telemetry shows "no data available"

### ISSUE THREAD

**Issue by BeigeBadger** [Azure/azure-iot-remote-monitoring#467]
As per [this issue](https://github.com/Azure/azure-iot-remote-monitoring/issues/462) my Telemetry, Alerts, and Analytics dashboard components are showing "No data available", even though data is flowing through to TSI.

I followed [this guide](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-integrate-time-series-insights) to Create an Event Source, Data Access Policy,  and Environment Variables. My Azure Stream Analytics is running but I couldn't complete step 5 of the [ASA section](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-integrate-time-series-insights#configure-azure-stream-analytics) because that query does not exist.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
