### ISSUE TITLE
Stop VM & Apps - Start & Get: Dashboard Configuration is Missing. Verify Contents of Webui-config.js

### ISSUE THREAD

**Issue by evogelpohl** [Azure/azure-iot-remote-monitoring#468]
Company policy is to shut down Azure $$ resources nightly via Azure Automation.
I created this Demo for IOT Remote Monitoring. We shut down the VM and the WebApps via a PowerShell nightly script:

If I restart the stopped items & attempt to open the IOT Remote Management URL - i get this.  Does this Demo not heal itself between restarts?  I have no clue what to do at this point...

<img width="440" alt="Screen Shot 2020-02-18 at 7 12 28 PM" src="https://user-images.githubusercontent.com/39970626/74789394-a246da80-5282-11ea-926c-e31ea9ee83bd.png">

**Comment by evogelpohl** [comment]
Following another link to learn how to SSH in and control the docker images.

**Comment by amitk-spektra** [comment]
@Evogelpohl I am also getting the same issue, I tried to deploy the soluation multiple times,, everytime after restarting the vm getting this issue

**Comment by evogelpohl** [comment]
Grrr, sorry @akn9050  - I haven't touched this in quite a while, moved on to other things. Looks like MS needs to make these demos more robust & tolerant of resources restarts. Best of luck to you.
