### ISSUE TITLE
Commandstatus remains pending

### ISSUE THREAD

**Issue by PdeBoerCGI** [Azure/azure-iot-remote-monitoring#49]
Hi,

Not sure if this is an issue, or that we are doing anything wrong. When we send a command to a device the command status remains pending. This happens when sending a command to a simulated device, but also to a custom device we wrote. The device is received correctly, but status is pending forever.

**Comment by jamesweb-ms** [comment]
This shouldn't be the case.  Which branch are you using?

**Comment by PdeBoerCGI** [comment]
This happens with the default provisioned solution. Either with a command sent to a default simulated device, but also with a device we built ourselves. The command is retrieved properly, but command status is always pending. 

We really wanted to try with a cloned version and our own deployment, but we had lots of different build/deployment issues with the current build.cmd file (from different branches). I noticed you are working on this, so we decided to wait until you merge the improvements into master.

**Comment by jamesweb-ms** [comment]
Please try with October-Integration.  We are planning to merge that with Master soon and do a release.  The backend service issue that was causing this should now be resolved.  Please let us know if you still see this with the October-Integration branch.
