### ISSUE TITLE
Occasional HTTP 401 errors updating document db

### ISSUE THREAD

**Issue by bmillerbma** [Azure/azure-iot-remote-monitoring#53]
The signature and header time stamps are not coordinated, and calls to the document db service occasionally fail with 401 errors.  The problem is compounded when you run the Debugger, depending upon where you put your break points.  

Please see the following fix:

https://github.com/bmillerbma/azure-iot-remote-monitoring/commit/5c2eabd04b17bfc832473098cc86a5f7c6fe6654

**Comment by jamesweb-ms** [comment]
Keith might have already fixed this.  He was working on some issues in that part of the code.

**Comment by keithcraig** [comment]
No, we didn't implement this fix yet, but it's a fine idea. We're integrating it into the current version of the file and are testing it now.

**Comment by jamesweb-ms** [comment]
This issue is now resolved in master
