### ISSUE TITLE
The stream analyics jobs must occasionally be restarted

### ISSUE THREAD

**Issue by bmillerbma** [Azure/azure-iot-remote-monitoring#54]
The stream analytics jobs occasionally stop processing events on the IoTHub.  The manifestation of this is that the telemetry graph stops updating or the alerts grid stops updating -- or never starts.  Restarting the jobs picks up events and starts.  The following commit adds a StartExistingStreamAnalyticsJobs () function to complement the StopExistingStreamAnalyticsJobs() function:

https://github.com/bmillerbma/azure-iot-remote-monitoring/commit/a981731175d1a32fc914ee7cb272568bd2d38a03

**Comment by jamesweb-ms** [comment]
This is a known issue with some backend services.  A fix has been partially deployed and they are working on getting this deployed world wide.  I'll update when we have verified this is resolved.  I'd rather not go the approach of stop/starting ASA jobs as this should not be an expected scenario.

**Comment by jamesweb-ms** [comment]
This service issue should now be resolved.  Please re-open if you see it happen again.
