### ISSUE TITLE
Min/Max Latitude & Longitude

### ISSUE THREAD

**Issue by dave1981** [Azure/azure-iot-remote-monitoring#58]
A little bug found in Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.BusinessLogic.DeviceLogic
If I set up all the devices, for example, in Europe, I get always -122.3 as minLong because all Longitudes in Europe are greater than 0.
I suggest to change the default values like these:
   double minLat = 181;
   double maxLat = -181;
   double minLong = 181;
   double maxLong = -181;

A little question as a newbie: is possible to compile and deploy all the projects except the "Web" one? For example, I change something in "Infrastructure" project and a colleague change something in "Web" project. Can we deploy separately without syncronize the code every time?

**Comment by keithcraig** [comment]
The maps issue was definitely a bug, and it has already been fixed on the `october-integration` branch which we are currently working on.

It's not possible to deploy the projects independently, due to project dependencies. For example, the Web project references the Infrastructure project.
