### ISSUE TITLE
What is the OSS license for this project?

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-iot-remote-monitoring#60]
Hi,
The `LICENSE.TXT` file (link: https://github.com/Azure/azure-iot-remote-monitoring/blob/master/license.txt) for this project looks like an end-user software licensing agreement (EULA) and not an open source license.

Is this project open source, and if so, can you:

- Update the license file appropriately (check with your legal contact, but often we have MIT licensed projects)
- Add headers to the source files to indicate that license and copyright

**Comment by MisinformedDNA** [comment]
Ping.

**Comment by aguilaaj** [comment]
See #125 - please read license.txt in the root directory.
Feel free to send a mail to iotsolhelp@microsoft.com if you have additional questions.
