### ISSUE TITLE
HTTP 405 "Method Not Allowed" Error When Bootstrapping a New DocumentDb Database

### ISSUE THREAD

**Issue by bmillerbma** [Azure/azure-iot-remote-monitoring#65]
When you create a new environment and spin up the simulator, the `CreateDeviceCollection()` method in `DocDbRestUtility` throws a HTTP 405 exception: "Method not allowed".  The exception only occurs the first time you attempt to spin up the environment.  On subsequent runs of the simulator, the `CreateDeviceCollection()` method does not get called b/c the logic skips the call if the database already exists, albeit without the collection!  I believe this fix solves the problem: dc758a63bf26cb850e04f19744de209119bef8f0

**Steps to Reproduce:**
1.  In the Azure portal, delete the DevMgmtDB database.  You may also need to delete the action table in blob storage too -- not sure.  I recall there is a hook to initialize the data if the actions are missing.
2.  Run the simulator

**Figure 1 -- Creating the document should set the _dbId member variable, not the _collectionId**

![image](https://cloud.githubusercontent.com/assets/15265832/10888959/1174bdec-815d-11e5-93d4-af6e17203208.png)

**Comment by jamesweb-ms** [comment]
Good catch.  You want to make a pull request off of October-Integration?
