### ISSUE TITLE
Build.cmd vs Build.ps1 user poll

### ISSUE THREAD

**Issue by jamesweb-ms** [Azure/azure-iot-remote-monitoring#67]
There has been a request to replace the build.cmd with a powershell version instead.  I'm biased and prefer powershell (which backs everything behind build.cmd), but there were requests in Private Preview to using build.cmd run through VSDev cmd shell.

This issue is to gauge feedback as to which one to use.  BMillerbma has already done the legwork to provide a PS interface and is advocating to replace the build.cmd with it.  I'm suspecting we might want to keep both, but would like feedback from those using the solution.  Please add a comment to this issue if you have a preference for one or the other.

**Comment by jamesweb-ms** [comment]
Adding one more option - VS extension so deployment happens through Visual Studio (not sure how much work this will be).

**Comment by networkfusion** [comment]
Personally I don't care so long as it would support continuous integration through VS Online ;-)

**Comment by gustafsonk** [comment]
I would definitely prefer the powershell version.

**Comment by TopperKain** [comment]
PowerShell would be better, but right now the Scripts don't work with Azure PowerShell 1.0. I'm working on touching them up to use the new Azure PowerShell command.

**Comment by jamesweb-ms** [comment]
You might want to hold off on the PS 1.0 work.  Doug from our team is getting close to having that done, and might be also adding direct PS deployment as well.  I'll have him update this thread when he has pushed a branch for testing.

**Comment by jamesweb-ms** [comment]
Postponing for now
