### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#73]
It would be good to add links to the documents like https://azure.microsoft.com/en-gb/documentation/articles/iot-suite-connecting-devices/ to the wiki.

In the documentation it also pertains to there being a repo with sample "real world" devices. It would also be good if a link to this repo was available on the wiki.

Also certain pages on the wiki say that they are only valid for the branch October integration, since v1 has been released, these warnings should be removed

**Comment by aguilaaj** [comment]
Done, thanks!
