### ISSUE TITLE
BingMaps not deployed to correct App Service Plan

### ISSUE THREAD

**Issue by rangedsp** [Azure/azure-iot-remote-monitoring#74]
When deploying using 

    build.cmd cloud release <deployment name>

The script tries to deploy BingMaps to my other app service plan, i.e. not <deployment name>-jobsplan nor <deployment name>-plan.

![image](https://cloud.githubusercontent.com/assets/4970707/11050682/efe18060-87ac-11e5-94d0-e13c4d92b8d0.png)

**Comment by jamesweb-ms** [comment]
This message is telling you that you have two instances of the bing maps plan (sku) "internal1" already, and you can't create another one.  Check to see how many Remote Monitoring solutions you have deployed in your solution.  Unfortunately you are currently limited to two with the free bing maps sku.

**Comment by rangedsp** [comment]
Thanks for the information, is it possible for you to document that somewhere, such as the wiki page for cloud deployment? I haven't seen any mention of the 2 deployment limit anywhere.

**Comment by aguilaaj** [comment]
Will do, thanks @rangedsp

**Comment by rangedsp** [comment]
Awesome thanks!
