### ISSUE TITLE
Support DocumentDB geolocation

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#76]
Currently you are storing a devices location using just the properties 'Longitude' and 'Latitude', I would recommend that the correct geolocation attribute (point type / co-ordinates) is used so that more efficient search can be carried out using documentDB and the storing of altitude is possible, e.g. https://code.msdn.microsoft.com/Geo-location-types-with-d3ea05a2

**Comment by aguilaaj** [comment]
Thanks for the feedback, unfortunately we are marking this issue as won't fix for the time being. If you'd like to implement the changes yourself, we will happily review pull requests. 
In addition, please post on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/) for others to upvote the priority of this ask.
