### ISSUE TITLE
Diagnostic Log

### ISSUE THREAD

**Issue by dave1981** [Azure/azure-iot-remote-monitoring#81]
I set the "Storage Settings" on my Web Application to a newly created blob. Every time I build a new version of my web app, this setting is deleted and I lost some important informations.
Is it a problem of the build operation? Or a bug of the platform?

**Comment by aguilaaj** [comment]
Hi Dave - apologies for the delay on this one - can you provide more detail? 
Curious what the changes are for the new blob and the motivation for swapping to a new one. Also, are you updating your build.cmd cloud config to point to your new blob as oppose to the old blob?

**Comment by aguilaaj** [comment]
@dave1981 - is this still an issue or can I close?

**Comment by aguilaaj** [comment]
Closing for now.
