### ISSUE TITLE
Get-AzureResourceGroup may not exist in new Azure PowerShell 1.0.1 release

### ISSUE THREAD

**Issue by hnakayam** [Azure/azure-iot-remote-monitoring#84]
Hi.

Now I started to build and deploy azure iot hub - remote monitoring demo, following the Wiki steps described below:
https://github.com/Azure/azure-iot-remote-monitoring/wiki

The build step was successful. But when I tried to deploy local i.e. "build.cmd local", the Azure PowerShell commandlet Get-AzureResourceGroup in DeploymentLib.ps1 failed.

Because Azure PowerShell 1.0.1 (November 2015) was released recently, that Get-AzureResourceGroup commandlet may be removed (or my environment is not upgraded from older version...).

Thanks.

**Comment by rangedsp** [comment]
You need to use PowerShell 0.9 for now. 
IIRC they are working on support for 1.0+ at the moment.

**Comment by aguilaaj** [comment]
This is currently in our backlog, thanks!

**Comment by hnakayam** [comment]
Hi,

I confirmed "build local" working in my environment when I tried PowerShell 0.9.8.1 (October 2015) release reinstalled.

Thanks!

**Comment by networkfusion** [comment]
Is there any update on when a fix for this will be available?

**Comment by rangedsp** [comment]
Just had this issue popping up after a long while, guess my azure powershell got auto updated.

**Comment by 0xbrock** [comment]
I ran into this issue last week and was going to wait for Microsoft to fix it, but it seems like they split the Service Management module from the Resource Manager model.  [How to install and configure Azure PowerShell](https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/) talks about how get the SM and RM modules setup with Azure Powershell 1.0 (upgrading from 0.9).

**Comment by jamesweb-ms** [comment]
Fixed with #111
