### ISSUE TITLE
Dates not regionalised

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#89]
For example:

CreatedTime (UTC) and UpdatedTime (UTC) within device properties are always show in American format (01/12/2016 11:49:47) where as if I was based in the UK I would expect to see the appropriate format (12/01/2016 11:49:47) as otherwise the user can be confused, especially if the day is less than 13!

**Comment by aguilaaj** [comment]
Thanks for calling this out, @networkfusion, we'll investigate.

**Comment by aguilaaj** [comment]
We added localized string support for the following in #151: 
•	Czech (Čeština) 
•	German (Deutsch)
•	English 
•	Spanish (Español) 
•	French (Français)
•	Hungarian (Magyar)
•	Italian (Italiano) 
•	Japanese (日本語) 
•	Dutch (Nederlands) 
•	Polish (Polski)
•	Portugese (Português) 
•	Russian (ру́сский)
•	Swedish (svenska)
•	Turkish (Türkçe)
•	Chinese simplified (中文(简体)) 
•	Chinese traditional (中文(簡體))

**Comment by networkfusion** [comment]
I still don't consider this report closed, the dates are still shown as mm/dd/yyyy for all languages in the device details pane (and probably other places). My Edge regional settings are set to en-GB

**Comment by aguilaaj** [comment]
Did you pull the latest from master? For the locations listed, the dates show up dd/mm/yyyy for example Italian etc.

**Comment by networkfusion** [comment]
yes, I pulled latest (12 hours ago) and dates are still all mm/dd/yyyy, even when using another European language (just checked Italian).

**Comment by jamesweb-ms** [comment]
@networkfusion - Can you see if this is now resolved for you based on Alex's fixes?

**Comment by networkfusion** [comment]
give me 48 hrs. I need to be stable until then...

**Comment by networkfusion** [comment]
I have just deployed again and most European languages display the date correctly as far as I can tell, except for English with an en-GB system local. Does this mean another resx needs creating for this?

**Comment by networkfusion** [comment]
any update on this?

**Comment by jamesweb-ms** [comment]
Fixed in PR #180

**Comment by aguilaaj** [comment]
@networkfusion - can you confirm dates are now appearing as expected?

**Comment by networkfusion** [comment]
@aguilaaj Unfortunately I am unable to confirm at the moment as the latest release breaks my ability to deploy using azure PS 1.5.0 (probably related in some way to #166 but when I deploy I am getting lots of empty string exceptions). My company is in the process of creating me a separate Azure account so I will test once I am up and running on that!

**Comment by networkfusion** [comment]
Actually, I have just deployed to my personal subscription (successfully as it is not multi-tenant) and dates are correctly displayed with the en-gb local! so this issue is indeed fixed! Thanks.
