### ISSUE TITLE
Consider using an open protocol for telemetry

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#90]
using an open standard like OM-JSON or OGC SensorThings would allow for better standards adoption from an example product.

**Comment by networkfusion** [comment]
Added feedback to https://feedback.azure.com/forums/321918-azure-iot/suggestions/11520663-azure-iot-remote-monitoring-consider-using-an-op

**Comment by aguilaaj** [comment]
Thanks, closing for now.
