### ISSUE TITLE
december intergration - device info not available for physical devices after upgrading from october intergration

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#91]
due to 

"SystemProperties": {
    "ICCID": null
  },

being added.

Consider adding a schema version to the device registry and an automatic upgrade thereof...

**Comment by aguilaaj** [comment]
@networkfusion Do you mean December-integration?

**Comment by aguilaaj** [comment]
Ah, title just refreshed. We'll take a look.

**Comment by aguilaaj** [comment]
@networkfusion can you validate this was fixed in https://github.com/Azure/azure-iot-remote-monitoring/releases/tag/v1.1.0 ?

**Comment by networkfusion** [comment]
@aguilaaj I will as soon as my azure msdn credits have been topped up which will be in about a week.

**Comment by aguilaaj** [comment]
Fixed in https://github.com/Azure/azure-iot-remote-monitoring/releases/tag/v1.1.0
