### ISSUE TITLE
Add at least one more example for a different (simulated) device with a different sensor telemetry

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#94]
To allow for easier development of different device/sensor types it would be helpful if the solution had a second simulated device showing a different sensor telemetry in the dashboard. this would allow a new developer to compare the two and derive a different type easier.

**Comment by aguilaaj** [comment]
Thanks for the suggestion, @networkfusion - to promote ideas like this, feel free to put them here: http://feedback.azure.com/forums/321918-azure-iot so others can upvote them. This helps us get an idea of the priority of suggested features and improvements.

**Comment by networkfusion** [comment]
added to https://feedback.azure.com/forums/321918-azure-iot/suggestions/11520609-azure-iot-remote-monitoring-solution-add-at-leas

**Comment by aguilaaj** [comment]
Great! Closing this for now.
