### ISSUE TITLE
Type name 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' is ambiguous

### ISSUE THREAD

**Issue by rangedsp** [Azure/azure-iot-remote-monitoring#95]
Running "build.cmd cloud release xxxx" is giving me the following error when listing out my AD instances. Looks like it's getting confused about different .dll versions.

![image](https://cloud.githubusercontent.com/assets/4970707/12404276/f1584c70-be9e-11e5-8f78-d241b5c93330.png)

**Comment by aguilaaj** [comment]
Hi @rangedsp - can you validate your dev environment compared to https://github.com/Azure/azure-iot-remote-monitoring/wiki/Set-up-development-environment-%28Windows%29 

Looks like the PowerShell cmd script for enumerating the Active Directories is confused.

**Comment by rangedsp** [comment]
@aguilaaj, I am using VS2015 even though for the last 6 months I can build without issue.
Yes to Azure SDK and PowerShell. 
I have multiple installations of Azure SDK (2.5, 2.6, 2.7, 2.8), which might have confused PS?

**Comment by aguilaaj** [comment]
Did you happen to have an instance of PowerShell already open when you tried to run build this time? Can you try to close other instances and run build from a new instance of PowerShell?

**Comment by levi106** [comment]
I have faced the same issue and I found a workaround.

1. Remove all directories from %USERPROFILE%\Documents\Nugets\
    (don't delete nuget.exe)
2. Open a command prompt window.
3. > CD %USERPROFILE%\Documents\Nugets\
4. > nuget.exe install Microsoft.IdentityModel.Clients.ActiveDirectory -Version 2.18.206251556
5. Run build.cmd

**Comment by rangedsp** [comment]
@levi106 thanks that worked for me, @aguilaaj there are no other PowerShell instances open when i ran the script.

Possible repo: install both Azure SDK 2.7 and 2.8, then run the script. I just repoed it on my home machine.

**Comment by levi106** [comment]
The error happened because there is two versions of assembly.

* %USERPROFILE%\Documents\Nugets\Microsoft.IdentityModel.Clients.ActiveDirectory.XX\lib\net45\
  * Version 2.19 or above (NuGet)
* %PROGRAMFILES(x86)\Microsoft SDKs\Azure\PowerShell\
  * version 2.18 (Microsoft Azure PowerShell 0.9.8.1)

I think it is better to fix the install script file DeploymentLib.ps1 (e.g. specify the version of the package to install or else).

**Comment by jamesweb-ms** [comment]
Fixed with #98

**Comment by rangedsp** [comment]
Vote to reopen this issue, just cloned the latest version in a new directory and the exact same error comes up.
